---
- uid: "ants/extrait_immatriculation_vehicule"
  opening: public
  call_id:
    - FranceConnect + Identifiant de l'immatriculation du véhicule
  parameters:
    - FranceConnect + Identifiant de l'immatriculation du véhicule
  path: "/api/v3/ants/extrait_immatriculation_vehicule/france_connect"
  ping_url: "https://particulier.api.gouv.fr/api/v3/ants/extrait_immatriculation_vehicule/ping"
  position: 603
  alert:
    title: "Usage exclusif pour la tarification du stationnement résidentiel"
    description: |+
      L’API SIV est actuellement en version restreinte, avec un nombre limité d’appels. Dans ce contexte, le déploiement progressif de cette API sera prévu à partir du premier trimestre 2026. Vous pouvez demander accès à cette API sur [lien formulaire pré rempli à insérer]. Nous vous tiendrons informés par mail de la date à partir de laquelle vous pourrez accéder aux données.

  perimeter:
    entity_type_description: |+
      Les données exposées par cette API proviennent du Système d’immatriculation des véhicules (SIV) pour les véhicules immatriculées après 2009 et du Fichier national des immatriculations (FNI) pour les véhicules immatriculées avant 2009. Ces fichiers sont placés sous la responsabilité du Ministère de l'intérieur.
      ⚠️ Cette API est à destination exclusive des collectivités dans la cadre de la tarification du stationnement résidentiel. Elle n'est pas à vocation de contrôle de droit à postériori de l'obtention d'un droit de stationnement.
      Cette API concerne les véhicules de particuliers immatriculés en France, que le particulier soit :&nbsp;
      ✅ propriétaire d'un véhicule particulier ;
      ✅ Co-titulaire d'un véhicule particulier ;
      ✅ locataire d'un véhicule en location longue durée (LLD, LCB, LCL) ou autre mode de location&nbsp.
      **Ne sont pas concernés :**
      ❌ les véhicules d'entreprise ou de fonction

    geographical_scope_description: |+
      L'API renvoie tous les extraits d'immatriculation des véhicules produits en France depuis [à compléter] :
      ✅ en France métropolitaine ;
      ✅ dans les DROM ;
      Ne sont pas renvoyés les extraits d'immatriculation des véhicules produits dans les :
      ❌ COM
      Les collectivités d'Outre-Mer disposent de leurs propres systèmes ou adaptations du SIV/FNI.
    updating_rules_description: |+
      Les données sont mises à jour :
      ✅  En temps réel lors de la requête (données à jour à l'instant T) ;
      ✅  En cas de changements (déménagement, nouveau véhicule etc.). La nouvelle donnée est disponible dès son enregistrement dans le SIV.
          L'API est connectée directement au SIV/FNI et dispose donc de la donnée la plus à jour possible.
      ⚠️  Les données transmises reflètent la situation connue au moment de l'appel. Une interrogation faite à un instant T peut donc différer d’une interrogation à T+1 en cas de changements.
    know_more_description: |+
      Lien optionnel pour en savoir plus sur la donnée. Le markdown GFM est supporté ici.

  parameters_details:
    description: |+
      Cette API est appelable uniquement avec le couple : [FranceConnect + identifiant d'immatriculation du véhicule (exemple : AA-123-BB)]

      <p class="fr-badge fr-badge--blue-ecume">FranceConnect + Identifiant d'immatriculation du véhicule</p>

  data:
    description: |+
      Cette API délivre des données fiables et à jour de l'extrait d'immatriculation d'un véhicule concernant :
      - l’identité du particulier (nom, prénom) ;
      - son adresse postale (au format La Poste);
      - son véhicule :
         - son immatriculation,
         - son statut d’usage (propriétaire ou locataire : LLD, LOA),
         - sa date de première immatriculation,
         - les caractéristiques techniques du véhicule (marque, modèle, type, cylindrée, carburant) ,
         - son taux d’émission de CO₂, masse maximale, catégorie (VP, M1, etc.),
         - sa norme environnementale (ex. Euro 6).
    know_more_description: |+
      [Informations présentes sur la carte grise qui sont dans le SIV](https://www.eplaque.fr/carte-grise/lire-une-carte-grise)

  # La liste des clés disponible est stockée dans la locale `provider_uids` du fichier provider_uids.fr.yml
  provider_uids:
    - "ants"
  keywords:
    - "immatriculation"
    - "siv"
    - "carte grise"
    - "stationnement résidentiel"
  faq:
    - q: "Question ?"
      a: |+
        Réponse à la question. Le markdown GFM est supporté ici.
  api_cgu:
    description: |+
      Les conditions d'utilisations spécifiques à l'API

