---
- uid: 'cnaf/allocation_soutien_familial'
  new_endpoint_uids:
    - 'cnaf_msa/allocation_soutien_familial'
  path: '/api/v2/allocation-soutien-familial'
  ping_url: 'https://particulier.api.gouv.fr/api/caf/ping'
  position: 100
  perimeter:
    entity_type_description:
    geographical_scope_description:
    updating_rules_description:
  parameters_details:
    description:
  data:
    description:
  provider_uids:
    - 'cnaf'
  keywords:
  parameters: Recipient + soit Identité pivot ou jeton FranceConnect
