---
- uid: 'cnaf/quotient_familial_v2'
  path: '/api/v2/composition-familiale-v2'
  # Position au sein de l'index
  position: 200
  perimeter:
    entity_type_description: |+
      Une description exhaustive des types d'entité renvoyés par le endpoint dans la fiche détaillée. Le markdown GFM est supporté ici.
    geographical_scope_description:  |+
      Une description exhaustive du scope géographique dans la fiche détaillée. Le markdown GFM est supporté ici.
    updating_rules_description: |+
      Les règles de mise à jour de la donnée dans al fiche détaillée. Le markdown GFM est supporté ici.
    know_more_description: |+
      Lien optionnel pour en savoir plus sur la donnée. Le markdown GFM est supporté ici.
  provider_uids:
    - 'cnaf'
  parameters:
    - Nom d'usage
    - Nom de naissance
    - Liste des prénoms
    - Année de naissance
    - Mois de naissance
    - Jour de naissance
    - Code INSEE du lieu de naissance
    - Code INSEE du pays de naissance
    - Genre
    - Année pour le quotient
    - Mois pour le quotient
  keywords:
    - composition
    - quotient
    - famille
    - familial
  use_cases:
    - Attribution des aides à la scolarité
    - Attribution des aides sociales
    - Tarification sociale et solidaire des transports
    - Tarification des services publics municipaux
  faq:
    - q: "Question ?"
      a: |+
        Réponse à la question. Le markdown GFM est supporté ici.
