---
- uid: 'cnaf_msa/quotient_familial_v2'
  new_version: true
  old_endpoint_uids:
    - 'cnaf/quotient_familial'
  path: '/api/v2/composition-familiale-v2'
  ping_url: 'https://particulier.api.gouv.fr/api/cnaf_msa_quotient_familial/ping'
  position: 200
  perimeter:
    entity_type_description: |+
      **Cette API concerne les allocataires de la majorité des régimes** :
      - ✅ le régime agricole (MSA) ;

      **À venir prochainement (T1 2024)** et disponibles durant la transition dans l'[ancienne API](/catalogue/cnaf/quotient_familial) :
      - ⏳ le régime général ;
      - ⏳ les titulaires de l'éducation nationale ;
      - ⏳ les retraités de la fonction publique d'État et des collectivités locales ;
      - ⏳ les régimes spéciaux suivants : artiste-auteur-compositeur, France Télécom, industries électriques et gazières, marin du commerce et pêche, mines (régime général), poste, RATP, SNCF, navigation intérieure en cas d'accord local et les pensions des autres régimes.


      **Ne sont pas concernés par cette API**, les bénéficiaires des régimes suivants :

      - ❌ le régime des titulaires de l'Assemblée nationale et du Sénat ;
      - ❌ le régime de la navigation intérieure **sauf** lorsqu'un accord local est passé, et que le régime est alors pris en compte par la CAF.

    geographical_scope_description:  |+
      - ✅ France métropolitaine
      - ✅ DROM COM
      - ✅ Allocataires de nationalité étrangère
    updating_rules_description: |+
      Les données sont **mises à jour en temps réel**, cette API opérée par la CNAV (Caisse nationale d'assurance vieillesse) est reliée au système d'information de la Caisse nationale des allocations familiales (CNAF) et à celui de la mutualité sociale agricole (MSA).

      ⚠️ **Les informations obtenues sont représentatives de la situation connue par la CNAF et la MSA au moment de l'appel**, il est donc possible qu'un quotient familial appelé pour un mois donné à un instant T, soit différent s'il est redemandé à un instant T+. [En savoir plus](faq_entry_1_api_particulier_endpoint_cnaf_msa_quotient_familial_v2).
  data:
    description: |+
      **Cette API délivre** : 
      - **la composition familiale** du particulier, [en savoir plus](#faq_entry_answer_2_api_particulier_endpoint_cnaf_msa_quotient_familial_v2) ;
      - **le quotient familial CAF ou MSA** du particulier. Par défaut, le quotient familial du **mois en cours** est transmis. Le QF de l'allocataire est disponible pour les 24 mois précédents en précisant le mois et l'année dans l'appel.

      {:.fr-highlight}
      > Le quotient familial au sens de la CNAF ou de la MSA a une définition différente du quotient familial de l'administration fiscale, [en savoir plus](#faq_entry_answer_0_api_particulier_endpoint_cnaf_msa_quotient_familial_v2).

      {:.fr-highlight.fr-highlight--caution}
      > **Le QF CNAF est calculé seulement pour les allocataires dont les ressources sont déclarées**. En effet, pour calculer le quotient familial, la CNAF collecte tous les mois auprès de la DGFIP les ressources de l'individu (revenus salariés et non-salariés, du capital, rentes ...). Elle récupère le bilan en fin d'année. Sans la réception de ces ressources, le QF CNAF ne peut être calculé : une erreur est renvoyée par l'API.
      >
      > Si le particulier n'a plus d'allocations, son QF n'est pas renvoyé. Une erreur est transmise par l'API.


  parameters_details:
    description: |+
      Cette API propose deux modalités d'appel :
      <p class="fr-badge fr-badge--green-emeraude">FranceConnect</p>
      **Avec FranceConnect**.

      <p class="fr-badge fr-badge--blue-ecume">Identité pivot</p>
      **Avec les données d'identité** : Noms, prénoms, sexe<sup>\*</sup>, date de naissance, code COG de la commune de naissance<sup>\**</sup> et code COG du pays de naissance<sup>\*</sup> de l'allocataire.
      <span class="fr-text--xs">
      <sup>\*</sup> Obligatoire | <sup>\**</sup> Obligatoire si la personne est née en France.
      </span>
      
      {:.fr-icon-arrow-right-line .fr-link--icon-right}
      [✒️ **Aider les usagers à renseigner leur lieu de naissance par code COG** - Lire la publication du 08/11/2023](https://particulier.api.gouv.fr/blog/parametre-lieu-naissance-code-cog){:target="_blank"}
  provider_uids:
    - 'cnaf_msa'
  parameters:
    - Identité pivot ;
    - ou FranceConnect.
  keywords:
    - composition
    - quotient
    - famille
    - familial
    - allocataire
    - enfant
    - adresse
  faq:
    - q: Quelle différence entre le quotient familial CAF/MSA et le QF de l'administration fiscale ?
      a: |+
        Le quotient familial retourné par l'API est le quotient familial de la CAF ou de la MSA. Ce QF est différent de celui de l'administration fiscale car il prend en compte les prestations familiales. Contrairement au quotient familial DGFIP calculé au moment de la déclaration de revenu, le QF CAF/MSA est revu à chaque changement de situation familiale et/ou professionnelle.

        Calcul du QF CAF/MSA : Revenu imposable de l’année N-2 divisé par 12 + **les prestations familiales du mois de référence**, le tout divisé par le nombre de parts fiscales du foyer.

        Source : [Caf.fr](https://caf.fr/allocataires/vies-de-famille/articles/quotient-familial-caf-impots-quelles-differences){:target="_blank"}

    - q: Variations du quotient familial au cours du temps et dates de calcul
      a: |+
        **Le quotient familial CAF ou MSA d'un même mois peut changer**. Il est recalculé fréquemment au cours du temps par la CAF et la MSA. En effet, la situation de la personne peut évoluer : _perte d'un emploi, évolution des ressources, arrivée d'un enfant, majorité d'un enfant, modification de la législation, évolution des allocations logement etc._
        **Cette variation apparaît notamment entre le quotient familial du mois en cours appelé en début de mois ou en fin de mois**.

        **Deplus, la date du calcul du quotient familial diffère** selon qu'il s'agit du quotient de la CAF ou de la MSA.
        - La CAF effectue une sauvegarde des quotients recalculés uniquement lorqu'un changement subvient du côté de l'allocataire.

            {:.fr-highlight.fr-highlight--example}
            > Par exemple, un appel le 28 juin 2023, du quotient du mois en cours (juin 2023) : La CAF renverra le QF qu'elle a en mémoire, par exemple calculé le 19 juin 2023.

        - La MSA effectue un recalcul du quotient familial à chaque appel de l'API.

            {:.fr-highlight.fr-highlight--example}
            > Par exemple, un appel le 28 juin 2023 du quotient familial du mois en cours (juin 2023) : la MSA recalculera le QF le 28 juin 2023.

    - q: Quelle est la composition familiale renvoyée par cette API ?
      a: |+
        La notion de «&nbsp;composition familiale&nbsp;» peut correspondre à différentes définitions dans les administrations qui n'y comptent pas les mêmes personnes. _Par exemple, pour calculer l'impôt sur le revenu d'un foyer, le service des impôts s'intéresse à une composition familiale appelée «&nbsp;foyer fiscal&nbsp;»_, et dont la nature est différente de celle renvoyée par cette API.
        
        **La composition familiale renvoyée par cette API correspond à celle établie pour effectuer le calcul du quotient familial, et donc à celle déclarée par les allocataires à la CAF et à la MSA.** 
        Dans cette composition familiale, les personnes suivantes sont comprises : 
        - L'adulte allocataire de la CAF ;
        - Son ou sa conjointe le cas échéant ;
        - Son ou ses enfants, dès la grossesse, jusqu'à 21 ans en métropole (22 dans les DROM) et sous les conditions détaillées dans [ce guide de la Caf](https://www.caf.fr/allocataires/aides-et-demarches/thematique-libre/les-enfants-charge){:target="_blank"}.

        **Pour chacune des personnes de cette famille**, cette API renvoie les informations suivantes : 
        - Nom d'usage ; 
        - Prénoms ; 
        - Jour, mois et année de naissance ;
        - Sexe.

  historique: |+
    **Ce que change cette API CNAF-MSA par rapport à l'API précédente de la CNAF :**
    - Le périmètre des particuliers concernés s'élargit avec l'**ajout des bénéficiaires de la MSA** qui sont au régime agricole.
    - **Les paramètres d'appel évoluent**. Dans l'API précédente, l'usager devait renseigner son numéro d'allocataire et son code postal. Avec cette API l'usager renseigne [ses données d'identité](#parameters_details).
