---
- uid: 'cnaf-msa/quotient_familial_v2'
  old_endpoint_uids:
    - 'cnaf/quotient_familial'
  path: '/api/v2/composition-familiale-v2'
  # Position au sein de l'index
  position: 500
  perimeter:
    entity_type_description: |+
      Cette API concerne les **allocataires de la majorité des régimes** :
      - ✅ le régime général ;
      - ✅ le régime agricole (MSA) ;
      - ✅ les titulaires de l'éducation nationale ;
      - ✅ les retraités de la fonction publique d'État et des collectivités locales ;
      - ✅ les régimes spéciaux suivants : artiste-auteur-compositeur, France Télécom, industries électriques et gazières, marin du commerce et pêche, mines (régime général), poste, RATP, SNCF, navigation intérieure en cas d'accord local et les pensions des autres régimes.

      Ne sont pas concernés par cette API, les bénéficiaires des régimes suivants :
      
      - ❌ le régime des titulaires de l'Assemblée nationale et du Sénat ;
      - ❌ le régime de la navigation intérieure **sauf** lorsqu'un accord local est passé, et que le régime est alors pris en compte par la CAF.

    geographical_scope_description:  |+
      - ✅ France métropolitaine
      - ✅ DROM COM
      - ✅ Allocataires de nationalité étrangère
    updating_rules_description: |+
      Les données sont **mises à jour en temps réel**, cette API opérée par la CNAV (Caisse nationale d'assurance vieillesse) est reliée au système d'information de la Caisse nationale des allocations familiales (CNAF) et à celui de la mutualité sociale agricole (MSA).

      ⚠️ **Les informations obtenues sont représentatives de la situation connue par la CNAF et la MSA et peuvent évoluer très fréquemment**. Le quotient familial CAF ou MSA est recalculé tous les mois, il peut être rétroactif et dépend de la situation du particulier et de l'état du droit. Il peut donc y avoir des écarts, notamment si la situation de la personne évolue entre temps : perte d'un emploi, évolution des ressources, arrivée d'un enfant, majorité d'un enfant, modification de la législation etc. Depuis que les allocations logement sont contemporaines (transmises très régulièrement), le QF est amené à évoluer lui aussi très fréquemment.
  data:
    description: |+
      Cette API délivre la **composition familiale de l'allocataire et son quotient familial CAF ou MSA**. Le QF de l'allocataire est disponible pour les 24 mois précédents en précisant le mois et l'année dans l'appel.

      {:.fr-highlight}
      > Le quotient familial au sens de la CNAF ou de la MSA a une définition différente du quotient familial de l'administration fiscale, [en  savoir plus](#faq_entry_1_api_particulier_endpoint_cnaf_quotient_familial).

      {:.fr-highlight.fr-highlight--caution}
      > **Le QF CNAF est calculé seulement pour les allocataires dont les ressources sont déclarées**. En effet, pour calculer le quotient familial, la CNAF collecte tous les mois auprès de la DGFIP les ressources de l'individu (revenus salariés et non-salariés, du capital, rentes ...). Elle récupère le bilan en fin d'année. Sans la réception de ces ressources, le QF CNAF ne peut être calculé : une erreur est renvoyée par l'API.
      >
      > Si le particulier n'a plus d'allocations, son QF n'est pas renvoyé. Une erreur est transmise par l'API.

      

  parameters_details:
    description: |+
      Cette API propose une modalité d'appel :
      <p class="fr-badge fr-badge--blue-ecume">Identité pivot</p>
      **Avec les données d'identité** : Noms, prénoms, date de naissance, code Insee de naissance et code pays de naissance de l'allocataire.
  provider_uids:
    - 'cnaf-msa'
  parameters:
    - Identité pivot
  keywords:
    - composition
    - quotient
    - famille
    - familial
    - allocataire
    - enfant
    - adresse
  use_cases:
    - Attribution des aides à la scolarité
    - Attribution des aides sociales
    - Tarification sociale et solidaire des transports
    - Tarification des services publics municipaux
  faq:
    - q: Quelle différence entre le quotient familial CAF/MSA et le QF de l'administration fiscale ?
      a: |+
        Le quotient familial retourné par l'API est le quotient familial de la CAF ou de la MSA. Ce QF est différent de celui de l'administration fiscale car il prend en compte les prestations familiales. Contrairement au quotient familial DGFIP calculé au moment de la déclaration de revenu, le QF CAF/MSA est revu à chaque changement de situation familiale et/ou professionnelle.

        Calcul du QF CAF/MSA : Revenu imposable de l’année N-2 divisé par 12 + **les prestations familiales du mois de référence**, le tout divisé par le nombre de parts fiscales du foyer.

        Source : [Caf.fr](https://caf.fr/allocataires/vies-de-famille/articles/quotient-familial-caf-impots-quelles-differences)
    - q: Qu'est-ce qu'un enfant au sens de la CNAF ?
      a: |+
        La liste des enfants transmis par l'API correspond à la notion d'enfant à charge au sens de la législation familiale. Pour qu'un enfant soit considéré comme "à charge", l’allocataire doit assurer financièrement son entretien de manière effective et permanente et assumer à son égard la responsabilité affective et éducative. Il n'y a pas d'obligation de lien de parenté avec l’enfant.

        Deux notions d’enfant à charge cohabitent :

        * enfant à charge au sens des prestations familiales (Pf) : un enfant est reconnu à charge s’il est âgé d’un mois à moins de 20 ans quelle que soit sa situation, dès lors que son salaire net mensuel ne dépasse pas 55 % du Smic brut ;
        * enfant à charge au sens de la législation familiale: en plus des enfants à charge au sens des Pf, sont également considérés à charge pour les aides au logement, les enfants âgés de moins de 21 ans en Métropole (22 ans dans les Dom), les enfants âgés de 20 à 25 ans pour le calcul du Rmi/Rsa, et dès le mois de leur naissance, les enfants bénéficiaires de l’allocation de base de la Paje.

        Source: [data.caf.fr](http://data.caf.fr/dataset/population-des-foyers-allocataires-par-commune/resource/3baa3b5b-8376-4b24-a79b-10ee364e956f)
  historique: |+
    **Ce que change cette API CNAF-MSA par rapport à l'API précédente de la CNAF :**
    - Le périmètre des particuliers concernés s'élargit avec l'**ajout des bénéficiaires de la MSA** qui sont au régime agricole.
    - **Les paramètres d'appel évoluent**. Dans l'API précédente, l'usager devait renseigner son numéro d'allocataire et son code postal. Avec cette API l'usager renseigne [ses données d'identité](#parameters_details).
