---
- uid: 'cnav/complementaire_sante_solidaire'
  opening: protected
  old_endpoint_uids:
    - 'cnav/v2/complementaire_sante_solidaire'
  path: '/v3/dss/complementaire_sante_solidaire/identite'
  position: 950
  ping_url: 'https://particulier.api.gouv.fr/api/securite_sociale_complementaire_sante_solidaire/ping'

  alert:
    title: "Correction en cours sur les données relatives à la participation financières"
    description: |+
      L’API retourne correctement le statut de bénéficiaire de la Complémentaire santé solidaire. Cependant, l’indication précisant si la personne bénéficie de la complémentaire avec ou sans participation financière peut, dans certains cas, ne pas refléter la situation réelle.
      Une évolution de l'API est prévue pour novembre 2025, afin d’améliorer la qualité de cette information. D'ici là, Si la distinction entre "avec" et "sans participation financière" est un critère déterminant pour l’attribution de votre aide ou service, il est recommandé de demander à l’usager de fournir une attestation à jour.

  perimeter:
    entity_type_description: |+
      ✅ **Le périmètre de l'API est exhaustif et couvre tous les assurés** de la sphère sociale susceptibles d'être concernés par la complémentaire de santé solidaire ([C2S](#faq_entry_0_api_particulier_endpoint_cnav_complementaire_sante_solidaire)).
    geographical_scope_description:  |+
      - ✅ France métropolitaine
      - ✅ Départements d'Outre-mer
      - ✅ Assurés de nationalité étrangère
      - ❌ Les collectivtés d'Outre-mer, ayant un autre système de sécurité sociale, ne sont pas concernées par cette API.
    updating_rules_description: |+
      Les données sont **mises à jour en temps réel** et issues du répertoire national commun de la protection sociale (RNCPS) opéré par la CNAV (Caisse nationale d'assurance vieillesse). Les données du répertoire sont remontées directement par les différents organismes comme la CNAM pour les assurés du régime général et la MSA pour les assurés au régime agricole.
  parameters_details:
    description: |+
      Cette API propose 2 modalités d'appel :
      <p class="fr-badge fr-badge--blue-ecume">![Cette API est FranceConnectée](<%= image_path('api_particulier/cas_usages/pictos/modalite_appel_france_connect.svg') %>){:width="20px"} FranceConnect</p>
      **Avec la [modalité d'appel FranceConnect](<%= cas_usage_path('modalite_appel_france_connect') %>)**.

      <p class="fr-badge fr-badge--brown-cafe-creme">Identité pivot</p>
      **Avec les données d'identité** : 
        
        {:.fr-mb-0}
        - Nom de naissance<sup>\*</sup>, nom d'usage, prénoms<sup>1</sup>, sexe<sup>\*</sup>, date de naissance de l'allocataire<sup>\**</sup>&nbsp;;
        - Lieu de naissance&nbsp;: 
            - *Si le lieu de naissance est en France,* la commune de naissance est obligatoire, elle peut être saisie de deux façons différentes :
                - {:.fr-text--sm .fr-mb-0} Option 1 : Code COG de la commune de naissance<sup>\*</sup>. [En savoir plus](#renseigner-lieu-de-naissance)&nbsp;;
                - {:.fr-text--sm .fr-mb-0} Option 2 : Nom de la commune de naissance<sup>\*</sup> et code du département de naissance<sup>\*</sup>. Pour cette option, la date de naissance est obligatoire. [En savoir plus](#renseigner-lieu-de-naissance).
                
              Pour chacune des deux options ci-dessus, le code COG de la France `99100`<sup>\*</sup> doit également être renseigné en paramètre d'appel. Vous n'avez pas besoin de le demander à l'usager, il peut être déduit de la commune de naissance.
            - *Si le lieu de naissance est à l'étranger&nbsp;:* code COG du pays de naissance<sup>\*</sup>.


      <span class="fr-text--xs">
      <sup>\*</sup> Obligatoire | <sup>\**</sup> Obligatoire pour l'option 2 du lieu de naissance.
      </span>
      <span class="fr-text--xs fr-m-0">
      <sup>1</sup> Fournir plusieurs prénoms permet de limiter les risques d'homonymie mais un seul prénom peut fonctionner. Attention, l'usager doit compléter chaque prénom dans un champ distinct.
      </span>
  data:
    description: |+
      Cette API **indique si le particulier est bénéficiaire de la complémentaire santé solidaire**. En précisant :
      - si la C2S est avec ou sans participation financière ;
      - la date d'ouverture du droit.
  provider_uids:
    - 'sphere_sociale'
  keywords:
    - complementaire
    - sante
    - solidaire
    - C2S
    - assuré
    - assurance maladie
    - mutuelle
  call_id:
    - Identité pivot
    - FranceConnect
  parameters:
    - Identité pivot
    - FranceConnect
  faq:
    - q: "Qu'est-ce qu'une complémentaire santé solidaire ?"
      a: |+
        La complémentaire santé solidaire est une **aide versée par l'assurance maladie sous conditions de ressources et de résidence**. Elle prend en charge la part des dépenses de santé qui ne sont pas remboursées par la sécurité sociale et permet d'accéder à d'autres avantages.

        La complémentaire santé solidaire peut être :
        - gratuite, indiquée par _"sans participation"_ dans cette API ;
        - payante à partir d'un certain montant de ressources, indiquée par _"avec participation"_ dans cette API.


        **En savoir plus sur le dispositif** : [service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F10027){:target="_blank"}.
        **En savoir plus sur les conditions d'accès** : [complementaire-sante-solidaire.gouv.fr](https://www.complementaire-sante-solidaire.gouv.fr/complementairesantesolidaire.php){:target="_blank"}.
    - q: <a name="renseigner-lieu-de-naissance"></a> Appel avec l'identité pivot, comment renseigner le lieu de naissance ?
      a: |+
       Lorsque l'API est appelée avec l'identité pivot, pour identifier correctement le particulier, le système d'information a besoin de récupérer le lieu de naissance du particulier.

        - **Pour les particuliers nés en France**: le code COG pays `99100` est obigatoire. La commune de naissance est également obligatoire et peut-être renseignée via deux options différentes&nbsp;:

            - *Option 1 : L'API est appelée avec le code COG commune lui-même*. Pour aider les usagers à renseigner leur code COG, consultez la publication suivante :
              {:.fr-icon-arrow-right-line .fr-link--icon-right}
              [✒️ **Aider les usagers à renseigner leur lieu de naissance par code COG** - Lire la publication du 08/11/2023](https://particulier.api.gouv.fr/blog/parametre-lieu-naissance-code-cog){:target="_blank"}

            - *Option 2 : L'API est appelée avec le nom de la commune de naissance et le code du département de naissance*. La date de naissance est obligatoire car c'est elle qui permettra à l'API de faire la correspondance avec le bon code COG.
        
        - **Pour les particuliers nés à l'étranger**: le code COG pays est obigatoire.

        {:.fr-highlight}
        > **Le code COG du pays de naissance est obligatoire pour tous les appels.** Pour simplifier le parcours des usagers, évitez de demander aux particuliers nés en France de saisir leur pays de naissance, puisque vous pouvez le paramétrer directement -code COG pays France `99100`-, dès qu'un particuloer renseigne les informations de sa commune de naissance (forcément en France).

  historique: |+
    **Ce que change le passage à la V.3 d'API Particulier:**

    - Suppression de la date de fin car cette donnée était calculée et présentait le risque de ne pas être juste dans toutes les situations ;
    - Tous les changements sont décrits dans la [table de correspondance du guide migration](/blog/migration-api-particulier-v3#correspondance-api-statut-c2s){:target="_blank"}


