---
- uid: 'cnav/complementaire_sante_solidaire'
  path: '/api/v2/complementaire-sante-solidaire'
  # Position au sein de l'index
  position: 200
  perimeter:
    entity_type_description: |+
      ✅ **Le périmètre de l'API est exhaustif et couvre tous les assurés** de la sphère sociale susceptibles d'être concernés par la complémentaire de santé solidaire.
    geographical_scope_description:  |+
      Cette API couvre les assurés : 
      - ✅ de France métropolitaine
      - ✅ des départements d'Outre-mer
      - ✅ de nationalité étrangère.

      Les collectivtés d'Outre-mer, ayant un autre système de sécurité sociale, ne sont pas concernées par cette API.
    updating_rules_description: |+
      Les données sont **mises à jour en temps réel** et issues du répertoire national commun de la protection sociale (RNCPS) opéré par la CNAV. Les données du répertoires sont remontées directement par les différents organismes comme par exemple la CNAF pour les assurés du régime général et la MSA pour les assurés au régime agricole.
  parameters_details:
    description: |+
      Cette API propose 2 modalités d'appel :
      <p class="fr-badge fr-badge--blue-ecume">Identité pivot</p>
      Avec les données d'identité : Noms, prénoms, sexe, date de naissance, code Insee de naissance et code pays de naissance du particulier.

      <p class="fr-badge fr-badge--green-emeraude">FranceConnect</p>
      Avec FranceConnect.
  data:
    description: |+
      Cette API **indique si le particulier est bénéfiaire de la complémentaire santé solidaire**, en précisant si celle-ci est avec ou sans participation finanicère. Si le particulier est bénéficaire, la date d'ouverture du droit et de fermeture du droit sera également transmise.
  provider_uids:
    - 'cnaf'
  # Ces mots clés servent à la recherche algolia sur l'index du catalogue
  keywords:
    - complementaire
    - sante
    - solidaire
  use_cases:
    - whatever
  faq:
    - q: "Question ?"
      a: |+
        Réponse à la question. Le markdown GFM est supporté ici.
