---
- uid: 'cnaf/sante_solidaire'
  path: '/api/v2/complementaire-sante-solidaire'
  # Position au sein de l'index
  position: 200
  perimeter:
    entity_type_description: |+
      Une description exhaustive des types d'entité renvoyés par le endpoint dans la fiche détaillée. Le markdown GFM est supporté ici.
    geographical_scope_description:  |+
      Une description exhaustive du scope géographique dans la fiche détaillée. Le markdown GFM est supporté ici.
    updating_rules_description: |+
      Les règles de mise à jour de la donnée dans al fiche détaillée. Le markdown GFM est supporté ici.
    know_more_description: |+
      Lien optionnel pour en savoir plus sur la donnée. Le markdown GFM est supporté ici.
  parameters_details:
    description: |+
      Cette API propose XXX modalités d'appel :
      <p class="fr-badge fr-badge--blue-ecume">Identité pivot</p>
      Avec les données d'identité du particulier : Lorem ipsum

      <p class="fr-badge fr-badge--purple-glycine">Identifiant</p>
      Avec TYPE IDENTIFIANT : Lorem ipsum

      <p class="fr-badge fr-badge--green-emeraude">FranceConnect</p>
      Avec FranceConnect.
  parameters_details:
    description: |+
      Cette API propose une modalité d'appel.
  data:
    description: |+
      Lorem ispum
  # La liste des clés disponible est stockée dans la locale `provider_uids` du fichier provider_uids.fr.yml
  provider_uids:
    - 'cnaf'
  # Ces mots clés servent à la recherche algolia sur l'index du catalogue
  keywords:
    - complementaire
    - sante
    - solidaire
  use_cases:
    - whatever
  faq:
    - q: "Question ?"
      a: |+
        Réponse à la question. Le markdown GFM est supporté ici.
