---
- uid: 'dsnj/service_national'
  opening: protected
  new_version: true
  path: '/v3/dsnj/service_national/identite'
  ping_url: 'https://particulier.api.gouv.fr/api/dsnj/service_national/ping'
  position: 600
  perimeter:
    entity_type_description: |+
      Cette API concerne les **✅ jeunes de 16 à 25 ans, de nationalité française**.

      **Ne sont pas concernés par cette API** :
      - ❌ les jeunes de nationalité étrangère ;
      - ❌ les personnes de moins de 16 et de plus de 25 ans car elles sont exemptées du service national.

    geographical_scope_description: |+
      - ✅ France métropolitaine ;
      - ✅ DROM COM ;
      - ✅ les français à l'étranger résidant dans un pays où il y a un consulat français qui organise des journées défense et citoyenneté. 
    updating_rules_description: |+
      **Les données sont mises à jour trimestriellement** car le processus de recensement est trimestriel.  
      
      {:.fr-highlight.fr-highlight--caution}
      > **⚠️ Un jeune en règle peut ne pas encore être déclaré comme tel par l'API en raison du délai de mise à jour.**
      > Du fait de la mise à jour trimestrielle, un jeune qui a fait son recensement, par exemple, _en janvier_ et qui a effectué sa journée défense et citoyenneté n'apparaîtra en règle dans l'API qu'_à partir du mois d'avril_. 
      > Dans ce cadre, nous recommandons aux administrations de **laisser la possibilité à l'usager de fournir un justificatif** si la réponse de l'API est `n'est pas en règle`. 
      
      Cette API est opérée par la direction du service national et de la jeunesse (DSNJ), les informations obtenues sont représentatives de la situation connue par la DSNJ au moment de l'appel. 
  data:
    description: |+
      Cette API indique : 
      - **si un jeune entre 16 et 25 ans est en règle de ses obligations de service national**, [en savoir plus](#service-national).
      - les commentaires laissés par XXX.

  parameters_details:
    description: |+
      Cette API propose deux modalités d'appel&nbsp;:
      <p class="fr-badge fr-badge--blue-ecume">![Cette API est FranceConnectée](<%= image_path('api_particulier/cas_usages/pictos/modalite_appel_france_connect.svg') %>){:width="20px"} FranceConnect</p>
      **Avec la [modalité d'appel FranceConnect](<%= cas_usage_path('modalite_appel_france_connect') %>)**.

      <p class="fr-badge fr-badge--brown-cafe-creme">Identité pivot</p>
      <section class="fr-accordion fr-mt-2v">
      <p class="fr-accordion__title">
      <button class="fr-accordion__btn" aria-expanded="false" aria-controls="accordion-106"><b>Avec les données d'identité</b></button>
      </p>
      <div class="fr-collapse" id="accordion-106">
      <div class="fr-mb-0">
      <ul>
      <li>Nom de naissance<sup>*</sup>, nom d'usage, prénoms<sup>1</sup>, sexe<sup>*</sup>, date de naissance de l'allocataire<sup>**</sup>&nbsp;;</li>
      <li>Lieu de naissance&nbsp;:
      <ul>
      <li>
      <em>Si le lieu de naissance est en France,</em> la commune de naissance est obligatoire, elle peut être saisie de deux façons différentes :
      <ul>
      <li class="fr-text--sm fr-mb-0">
      Option 1 : Code COG de la commune de naissance<sup>*</sup>. <a href="#renseigner-lieu-de-naissance">En savoir plus</a>&nbsp;;
      </li>
      <li class="fr-text--sm fr-mb-0">
      Option 2 : Nom de la commune de naissance<sup>*</sup> et code du département de naissance<sup>*</sup>. Pour cette option, la date de naissance est obligatoire. <a href="#renseigner-lieu-de-naissance">En savoir plus</a>.
      </li>
      </ul>
      Pour chacune des deux options ci-dessus, le code COG de la France <code>99100</code><sup>*</sup> doit également être renseigné en paramètre d'appel. Vous n'avez pas besoin de le demander à l'usager, il peut être déduit de la commune de naissance.
      </li>
      <li class="fr-mt-2v">
      <em>Si le lieu de naissance est à l'étranger&nbsp;:</em> code COG du pays de naissance<sup>*</sup>.
      </li>
      </ul>
      </li>
      </ul>
      </div>
      <span class="fr-text--xs">
      <sup>*</sup> Obligatoire | <sup>**</sup> Obligatoire pour l'option 2 du lieu de naissance.
      </span>
      <span class="fr-text--xs fr-m-0">
      <sup>1</sup> Fournir plusieurs prénoms permet de limiter les risques d'homonymie mais un seul prénom peut fonctionner. Attention, l'usager doit compléter chaque prénom dans un champ distinct.
      </span>
      <blockquote class="fr-highlight fr-highlight--caution">
      ⚠️ <strong>Message API Particulier du 04.06.2024</strong> : Nous avons constaté que les appels effectués sans nom de naissance et <strong>avec le nom d'usage ne fonctionnent pas</strong> dans une très grande partie des cas. API Particulier a donc décidé de passer le paramètre "Nom de naissance" en obligatoire.
      </blockquote>
      </div>
      </section>

  provider_uids:
    - 'dsnj'
  call_id: 
    - Identité pivot
    - FranceConnect
  parameters:
    - Identité pivot
    - FranceConnect
  keywords:
    - service national
    - jeune
    - jdc
    - Journée défense et citoyenneté

  faq:
    - q: <a name="service-national"></a>Qu'est-ce que le service national ?
      a: |+
        **Le service national est composé du rencensement et de la participation à la journée défense et citoyenneté. Un jeune qui est en règle vis à vis du service national a donc effectué son recensement dès l'âge de 16 ans et a participé à la journée défense et citoyenneté**. [Plus d'informations](https://www.service-public.fr/particuliers/vosdroits/N24)

    - q: <a name="faq-pourquoi-etre-en-regle"></a> Pourquoi un jeune doit être en règle vis à vis du service national ? 
      a: |+
        **Un jeune entre 16 et 25 ans doit être en règle vis à vis du service national s'il souhaite : 
        - passer des examens sous contrôle de l'autorité publique comme le permis de conduire ;
        - passer des concours sous contrôle de l'autorité publique, pour rentrer dans un établissement public de l'enseignement supérieur par exemple ;
        - postuler à un emploi de la fonction publique qui demande d'être en règle vis à vis du service national. 
        [Plus d'informations](https://www.data.gouv.fr/fr/dataservices/api-service-national/)

    - q: Une personne qui a une dérogation de faire la journée défense et citoyenneté, pour cause médicale par exemple, est elle remontée comme étant en règle ? 
      a: |+
        **Un jeune exempté de la JDC apparaîtra comme étant en règle dans l'API**
