---
- uid: 'education_nationale/statut_eleve_scolarise_v2'
  opening: protected
  path: '/api/v2/scolarites_v2'
  ping_url: 'https://particulier.api.gouv.fr/api/men_scolarite_v2/ping'
  position: 501
  perimeter:
    entity_type_description: |+
      Lorem
    geographical_scope_description:  |+
      Ipsum
    updating_rules_description: |+
      Lorem
  parameters_details:
    description: |+
      Ipsum
  data:
    description: |+
      Lorem
  provider_uids:
    - 'education_nationale'
  keywords: []
  call_id:
    - Identité pivot
    - FranceConnect
  parameters:
    - Identité pivot
  faq:
    - q: Lorem????
      a:
        Ipsum!
