---
- uid: 'pole_emploi/situation'
  path: '/api/v2/situations-pole-emploi'
  position: 400
  perimeter:
    entity_type_description: |+
      L'API concerne **les demandeurs d'emploi ayant été inscrits à Pôle emploi depuis 2010**, y compris ceux dont l'inscription a pris fin. 
      
      **Seules les cinq premières catégories de demandeurs d'emploi sont concernées** par l'API : 
      - ✅ en recherche d'emploi ;
      - ✅ disponibles immédiatement ;
      - ✅ non-tenus de faire des actes positifs de recherche d’emploi.

      Les ❌ catégories 6 à 8, tenues d'accomplir des actes positifs de recherche d'emploi, ne sont pas concernées par l'API. [En savoir plus](#faq_entry_0_api_particulier_endpoint_pole_emploi_situation).

    geographical_scope_description:  |+
      - ✅ France métropolitaine ;
      - ✅ DROM COM ;
      - ✅ travailleurs étrangers ressortissant d'un pays européen (membre de l’Union Européenne, de l’espace économique européen, de la Suisse, Monaco, Andorre ou Saint-Martin) ou ayant [les titres et autorisations nécessaires](https://www.pole-emploi.fr/candidat/mes-droits-aux-aides-et-allocati/a-chaque-situation-son-allocatio/quelle-est-ma-situation-personne/je-suis-travailleur-etranger--pu.html) pour être inscrit à Pôle emploi.


    updating_rules_description: |+
      Les données sont **mises à jour en temps réel**, l'API étant directement reliée au système d'information de Pôle emploi.

      Les informations obtenues sont représentatives de la situation à date du demandeur d'emploi. Par exemple, la catégorie d'inscription, donnée qui peut évoluer au cours du temps, est mise à jour en temps réel également.
  parameters_details:
    description: |+
      Cette API propose une seule modalité d'appel :
      <p class="fr-badge fr-badge--purple-glycine">Identifiant</p>
      **Avec l'identifiant Pôle emploi** : Cet identifiant est celui choisi par le particulier lors de la création de son espace personnel en ligne.
  data: 
    description: |+
      Pour les demandeurs d'emploi actuels, l'API renvoie la **date d'inscription et la catégorie** permettant de connaître la situation précise du demandeur, ainsi que des informations concernant le demandeur d'emploi.

      L'API transmettant des données sur les demandeurs d'emploi inscrits depuis 2010, elle peut également délivrer des informations sur les demandeurs d'emploi dont l'inscription a pris fin.
      Dans ce cas, seules les dates d'inscription et de cessation d'inscription sont renvoyées.
      
      {:.fr-highlight}
      > La durée de conservation des données des demandeurs d'emploi va prochainement évoluer dans le cadre de la mise en œuvre du droit à l’oubli.

  provider_uids:
    - 'pole_emploi'
  parameters:
    - Identifiant Pôle emploi
  keywords: []
  use_cases:
    - Attribution des aides à la scolarité
    - Attribution des aides sociales
    - Tarification sociale et solidaire des transports
    - Tarification des services publics municipaux
  faq:
    - q: Périmètre détaillé des catégories de demandeurs d'emploi concernés par l'API.
      a: |+
        Les catégories de demandeur d'emploi délivrées par l'API correspondent aux 5 premières catégories administratives définies par l’[arrêté du 5 février 1992 portant application de l’article L. 5411-2 du Code du travail](https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000174464/) :

        {:.fr-table}
        | Catégorie administrative    | Description       |  Catégorie présente dans l'API|
        | --------------------------------------- | -------------------------------------- |------------------------------ |
        | 1           | Personnes sans emploi, immédiatement disponibles, tenues d'accomplir des actes positifs de recherche d'emploi, à la **recherche d'un emploi à durée indéterminée à plein temps**.   |  ✅  |
        | 2          | Personnes sans emploi, immédiatement disponibles, tenues d'accomplir des actes positifs de recherche d'emploi, à la **recherche d'un emploi à durée indéterminée à temps partiel**. |  ✅  |
        | 3          | Personnes sans emploi, immédiatement disponibles, tenues d'accomplir des actes positifs de recherche d'emploi, à la **recherche d'un emploi à durée déterminée temporaire ou saisonnier, y compris de très courte durée**. |  ✅  |
        | 4          | Personnes sans emploi, **non immédiatement disponibles**, à la recherche d'un emploi.|  ✅  |
        | 5          | Personnes **pourvues d'un emploi, à la recherche d'un autre emploi.** |  ✅  |
        | 6          | Personnes non immédiatement disponibles à la recherche d'un autre emploi, à durée indéterminée à plein temps, tenues d'accomplir des actes positifs de recherche d'emploi. |  ❌  |
        | 7          | Personnes non immédiatement disponibles à la recherche d'un autre emploi, à durée indéterminée à temps partiel, tenues d'accomplir des actes positifs de recherche d'emploi.  |  ❌  |
        | 8          | Personnes non immédiatement à la recherche d'un autre emploi, à durée déterminée, temporaire ou saisonnier, y compris de très courte durée, tenues d'accomplir des actes positifs de recherche d'emploi.  |  ❌  |


