---
- uid: 'pole_emploi/situation'
  path: '/api/v2/situations-pole-emploi'
  ping_url: 'https://particulier.api.gouv.fr/api/pole_emploi_status/ping'
  position: 700
  perimeter:
    entity_type_description: &pole_emploi__entity_type_description |+
      L'API concerne **les demandeurs d'emploi ayant été inscrits à Pôle emploi depuis 2010**, y compris ceux dont l'inscription a pris fin.

      **Seules les [cinq premières catégories de demandeurs d'emploi](#faq_entry_answer_0_api_particulier_endpoint_pole_emploi_situation) sont concernées** par l'API :
      - ✅ en recherche d'emploi ;
      - ✅ disponibles immédiatement ;
      - ✅ non-tenus de faire des actes positifs de recherche d’emploi.

      Les ❌ catégories 6 à 8, tenues d'accomplir des actes positifs de recherche d'emploi, ne sont pas concernées par l'API. [En savoir plus](#faq_entry_0_api_particulier_endpoint_pole_emploi_situation).

    geographical_scope_description: &pole_emploi_geographical_scope_description |+
      - ✅ France métropolitaine ;
      - ✅ DROM COM ;
      - ✅ travailleurs étrangers ressortissant d'un pays européen (membre de l’Union Européenne, de l’espace économique européen, de la Suisse, Monaco, Andorre ou Saint-Martin) ou ayant [les titres et autorisations nécessaires](https://www.pole-emploi.fr/candidat/mes-droits-aux-aides-et-allocati/a-chaque-situation-son-allocatio/quelle-est-ma-situation-personne/je-suis-travailleur-etranger--pu.html) pour être inscrit à Pôle emploi.


    updating_rules_description: &pole_emploi_updating_rules_description |+
      Les données sont **mises à jour en temps réel**, l'API étant directement reliée au système d'information de Pôle emploi.

      Les informations obtenues sont représentatives de la situation à date du demandeur d'emploi. Par exemple, la catégorie d'inscription, donnée qui peut évoluer au cours du temps, est mise à jour en temps réel également.
  parameters_details:
    description: |+
      Cette API propose une seule modalité d'appel :
      <p class="fr-badge fr-badge--purple-glycine">Identifiant</p>
      **Avec l'identifiant du compte utilisateur Pôle emploi** : Cet identifiant est celui choisi par le particulier lors de la création de son espace personnel en ligne.


      <section class="fr-accordion">
       <h3 class="fr-accordion__title">
        <button class="fr-accordion__btn" aria-expanded="false" aria-controls="accordion-106">
         Besoin de cette API avec FranceConnect ?
        </button>
       </h3>
       <div class="fr-collapse" id="accordion-106">
        La modalité d'appel FranceConnect n'est pas disponible pour l'API demandeur d'emploi sur API Particulier.

        Vous pouvez utiliser l'[API dédiée de Pôle emploi](https://api.gouv.fr/les-api/api-statut-demandeur-emploi){:target="_blank"} ! Cette API, qui n'appartient pas au bouquet API Particulier, permet d'accéder au statut demandeur d'emploi avec FranceConnect. Il vous faudra faire une habilitiation spécifique.
       </div>
      </section>

  data:
    description: |+
      Pour les demandeurs d'emploi actuels, l'API renvoie la **date d'inscription et la catégorie** permettant de connaître la situation précise du demandeur, ainsi que des informations concernant le demandeur d'emploi.

      L'API transmettant des données sur les demandeurs d'emploi inscrits depuis 2010, elle peut également délivrer des informations sur les demandeurs d'emploi dont l'inscription a pris fin.
      Dans ce cas, seules les dates d'inscription et de cessation d'inscription sont renvoyées.

      {:.fr-highlight}
      > La durée de conservation des données des demandeurs d'emploi va prochainement évoluer dans le cadre de la mise en œuvre du droit à l’oubli.

  provider_uids:
    - 'pole_emploi'
  parameters:
    - Identifiant Pôle emploi.
  keywords: []
  use_cases:
    - Attribution des aides à la scolarité
    - Attribution des aides sociales
    - Tarification sociale et solidaire des transports
    - Tarification des services publics municipaux
  faq:
    - q: &pole_emploi_faq_q_1 Périmètre détaillé des catégories de demandeurs d'emploi concernés par l'API.
      a: &pole_emploi_faq_r_1 |+
        Les catégories de demandeur d'emploi délivrées par l'API correspondent aux 5 premières catégories administratives définies par l’[arrêté du 5 février 1992 portant application de l’article L. 5411-2 du Code du travail](https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000174464/){:target="_blank"} :

        {:.fr-table}
        | Catégorie administrative    | Description       |  Catégorie présente dans l'API|
        | --------------------------------------- | -------------------------------------- |------------------------------ |
        | 1           | Personnes sans emploi, immédiatement disponibles, tenues d'accomplir des actes positifs de recherche d'emploi, à la **recherche d'un emploi à durée indéterminée à plein temps**.   |  ✅  |
        | 2          | Personnes sans emploi, immédiatement disponibles, tenues d'accomplir des actes positifs de recherche d'emploi, à la **recherche d'un emploi à durée indéterminée à temps partiel**. |  ✅  |
        | 3          | Personnes sans emploi, immédiatement disponibles, tenues d'accomplir des actes positifs de recherche d'emploi, à la **recherche d'un emploi à durée déterminée temporaire ou saisonnier, y compris de très courte durée**. |  ✅  |
        | 4          | Personnes sans emploi, **non immédiatement disponibles**, à la recherche d'un emploi.|  ✅  |
        | 5          | Personnes **pourvues d'un emploi, à la recherche d'un autre emploi.** |  ✅  |
        | 6          | Personnes non immédiatement disponibles à la recherche d'un autre emploi, à durée indéterminée à plein temps, tenues d'accomplir des actes positifs de recherche d'emploi. |  ❌  |
        | 7          | Personnes non immédiatement disponibles à la recherche d'un autre emploi, à durée indéterminée à temps partiel, tenues d'accomplir des actes positifs de recherche d'emploi.  |  ❌  |
        | 8          | Personnes non immédiatement à la recherche d'un autre emploi, à durée déterminée, temporaire ou saisonnier, y compris de très courte durée, tenues d'accomplir des actes positifs de recherche d'emploi.  |  ❌  |

- uid: 'pole_emploi/indemnites'
  path: '/api/v2/paiements-pole-emploi'
  ping_url: 'https://particulier.api.gouv.fr/api/pole_emploi_indemnites/ping'
  position: 501
  perimeter:
    entity_type_description: |+
      L'API concerne **les demandeurs d'emploi ayant été inscrits à Pôle emploi depuis 2010**, y compris ceux dont l'inscription a pris fin.

      **Toutes les [catégories de demandeurs d'emploi](#faq_entry_answer_0_api_particulier_endpoint_pole_emploi_indemnites) sont concernées** par l'API :
      - ✅ en recherche d'emploi ;
      - ✅ disponibles immédiatement ;
      - ✅ non-tenus de faire des actes positifs de recherche d’emploi ;
      - ✅ tenues d'accomplir des actes positifs de recherche d'emploi.

    geographical_scope_description: *pole_emploi_geographical_scope_description
    updating_rules_description: Les données sont **mises à jour en temps réel**, l'API étant directement reliée au système d'information de Pôle emploi.Les informations obtenues sont représentatives de la situation à date des paiements versés au demandeur d'emploi.
  parameters_details:
    description: |+
      Cette API propose une seule modalité d'appel :

      <p class="fr-badge fr-badge--purple-glycine">Identifiant</p>
      **Avec l'identifiant du compte utilisateur Pôle emploi** : Cet identifiant est celui choisi par le particulier lors de la création de son espace personnel en ligne.
      ⚠️ Pour utiliser cette API, il est indispensable de recouper ce paramètre d'appel avec l'identité du particulier. [Consulter les CGU spécifiques](#api_cgu).

      <section class="fr-accordion">
        <h3 class="fr-accordion__title">
        <button class="fr-accordion__btn" aria-expanded="false" aria-controls="accordion-106">
          Besoin de cette API avec FranceConnect ?
        </button>
        </h3>
        <div class="fr-collapse" id="accordion-106">
        La modalité d'appel FranceConnect n'est pas disponible pour l'API demandeur d'emploi sur API Particulier.

        Vous pouvez utiliser l'[API dédiée de Pôle emploi](https://api.gouv.fr/les-api/api-indemnisation-pole-emploi){:target="_blank"} ! Cette API, qui n'appartient pas au bouquet API Particulier, permet d'accéder à la liste des paiements versés avec FranceConnect. Il vous faudra faire une habilitiation spécifique.
        </div>
      </section>
  data:
    description: |+
      Cette API délivre la **liste des paiements Pôle emploi** du demandeur d'emploi. L'historique maximal est de 24 mois. Ces paiements sont datés et répartis en 3 catégories (allocations, aides et autres paiements).

      {:.fr-highlight}
      > **Cas particuliers :**
      > - Si l'API est appelée pour un demandeur d'emploi qui n'est plus inscrit, l'API renvoie uniquement la liste de paiements de sa dernière inscription.
      > - Comme sur le compte utilisateur du demandeur d'emploi, il peut arriver que pour un appel en fin de mois, un paiement soit visible en anticipation, avec une date le mois suivant.

  provider_uids:
    - 'pole_emploi'
  parameters:
    - Identifiant Pôle emploi.
  keywords: []
  use_cases:
    - Attribution des aides à la scolarité
    - Attribution des aides sociales
    - Tarification sociale et solidaire des transports
    - Tarification des services publics municipaux
  faq:
    - q: Périmètre détaillé des catégories de demandeurs d'emploi concernés par l'API.
      a: |+
        Les catégories de demandeur d'emploi délivrées par l'API correspondent aux 8 catégories administratives définies par l’[arrêté du 5 février 1992 portant application de l’article L. 5411-2 du Code du travail](https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000174464/){:target="_blank"} :

        {:.fr-table}
        | Catégorie administrative    | Description       |  Catégorie présente dans l'API|
        | --------------------------------------- | -------------------------------------- |------------------------------ |
        | 1           | Personnes sans emploi, immédiatement disponibles, tenues d'accomplir des actes positifs de recherche d'emploi, à la **recherche d'un emploi à durée indéterminée à plein temps**.   |  ✅  |
        | 2          | Personnes sans emploi, immédiatement disponibles, tenues d'accomplir des actes positifs de recherche d'emploi, à la **recherche d'un emploi à durée indéterminée à temps partiel**. |  ✅  |
        | 3          | Personnes sans emploi, immédiatement disponibles, tenues d'accomplir des actes positifs de recherche d'emploi, à la **recherche d'un emploi à durée déterminée temporaire ou saisonnier, y compris de très courte durée**. |  ✅  |
        | 4          | Personnes sans emploi, **non immédiatement disponibles**, à la recherche d'un emploi.|  ✅  |
        | 5          | Personnes **pourvues d'un emploi, à la recherche d'un autre emploi.** |  ✅  |
        | 6          | Personnes non immédiatement disponibles à la recherche d'un autre emploi, à durée indéterminée à plein temps, tenues d'accomplir des actes positifs de recherche d'emploi. |   ✅   |
        | 7          | Personnes non immédiatement disponibles à la recherche d'un autre emploi, à durée indéterminée à temps partiel, tenues d'accomplir des actes positifs de recherche d'emploi.  |   ✅   |
        | 8          | Personnes non immédiatement à la recherche d'un autre emploi, à durée déterminée, temporaire ou saisonnier, y compris de très courte durée, tenues d'accomplir des actes positifs de recherche d'emploi.  |   ✅   |
  api_cgu:
    description: |+
        Il est **indispensable de recouper l'identifiant du compte utilisateur Pôle Emploi avec l'identité du particulier** avant d'utiliser cette API.

        En effet, cette API est appelable avec un seul paramètre d'appel, l'identifiant du compte utilisateur Pôle Emploi. Par conséquent, si vous n'avez pas pu établir que cet identifiant utilisé en appel correspond bien au particulier concerné, vous prenez le risque de lui transmettre les données d'un autre allocataire.

        {:.fr-highlight.fr-highlight--caution}
        > **En utilisant cette API, vous vous engagez donc à recouper l'identifiant du compte utilisateur Pôle Emploi avec l'identité du particulier** en faisant un appel en parallèle sur l'[API statut demandeur d'emploi](../pole_emploi/situation).
        > En effet, cette autre API permet d'accéder aux deux informations.
        >
        > À notre connaissance, l'identifiant du compte utilisateur est configuré par l'usager au moment de la création de son espace et n'est donc présent sur aucun document ou courriel qui permettrait à un agent de vérifier l'identité. L'appel à l'API statut demandeur d'emploi est donc indispensable pour vérifier l'identité.


