---
- uid: 'pole_emploi/situation'
  path: '/api/v2/situations-pole-emploi'
  position: 400
  perimeter:
    entity_type_description: |+
      L’API délivre des informations sur les ✅ **personnes inscrites comme demandeur d’emploi**.

      Cela signifie que l'API transmet des informations sur les demandeurs d'emploi :
      - en recherche d'emploi ;
      - qui ne sont pas disponibles immédiatement ;
      - qui ne sont pas tenus de faire des actes positifs de recherche d’emploi.

      L'API renvoie la catégorie du demandeur d'emploi permettant justement de déterminer la situation précise du demandeur.

      ℹ️ L'API délivre des informations sur les demandeurs d'emploi ayant été inscrits à Pôle emploi depuis 2010, y compris ceux dont l'inscription a pris fin. Dans ce cas, seules les dates d'inscription et de cessation d'inscription sont renvoyées.
      Actuellement, la durée de conservation de ces données (durée prévues à l’[article R. 5312-44 du code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032625875/) relatif au système d’information de Pôle emploi) va être amenée à changer, suite à la mise en œuvre du droit à l’oubli, travaux en cours.

    geographical_scope_description:  |+
      **Tous les demandeurs d'emploi** sont concernés :
      - ✅ France métropolitaine
      - ✅ DROM COM
      - ✅ Travailleurs étrangers ressortissant d'un européen (membre de l’Union Européenne, de l’Espace économique européen, de la Suisse, Monaco, Andorre ou Saint- Martin) ou ayant [les titres et autorisations nécessaires](https://www.pole-emploi.fr/candidat/mes-droits-aux-aides-et-allocati/a-chaque-situation-son-allocatio/quelle-est-ma-situation-personne/je-suis-travailleur-etranger--pu.html) pour être inscrits à pôle emploi.


    updating_rules_description: |+
      Les données sont **mises à jour en temps réel**, l'API étant directement reliée au système d'information de Pôle emploi.

      Les informations obtenues sont représentatives de la situation à date du demandeur d'emploi. Par exemple, la catégorie d'inscription, donnée qui peut évoluer au cours du temps, est mise à jour en temps réel également.

  provider_uids:
    - 'pole_emploi'
  parameters:
    - Identifiant Pôle Emploi
  keywords: []
  use_cases:
    - Attribution des aides à la scolarité
    - Attribution des aides sociales
    - Tarification sociale et solidaire des transports
    - Tarification des services publics municipaux
  faq: []
