---
- uid: 'sport_data_hub/statut_sportif'
  opening: protected
  novelty: true
  call_id:
    - Identifiant PSQS
  parameters:
    - Identifiant PSQS
  path: '/v3/sdh/statut_sportif/identifiant'
  position: 601
  perimeter:
    entity_type_description: |+
      Cette API concerne tous les sportifs de nationalité française ou étrangère dont le statut, reconnu par le ministère des sports, est le suivant : 
      - ✅ les **sportifs sur liste ministérielle** : **sportif de haut niveau** (SHN), **sportif inscrit en liste Espoirs** (SE), **sportif inscrit en liste des Collectifs Nationaux** (SCN) ;
      - ✅ les **sportifs du parcours de performance fédéral** (PPF) ;
      - ✅ les **arbitre-juge de haut niveau** (AJSHN). 
      [Plus d'informations sur les différents statuts et catégories des sportifs reconnu par le minstère des sports](https://www.sports.gouv.fr/mises-en-listes-ministerielles-1838)

      L'API couvre les sportifs **de tout âge, y compris les mineurs**.

    geographical_scope_description:  |+
      - ✅ France métropolitaine
      - ✅ DROM COM

    updating_rules_description: |+
      Les données sont **mises à jour une fois par an**, selon la saison sportive :
      - Sports d’hiver : du 1er juillet de l’année N au 30 juin de l’année N+1 ;
      - Sports d’été : du 1er janvier au 31 décembre.
      Les données sont valables un an, sur l'année scolaire en général, sauf le statut du sportif de haut niveau de la catégorie élite qui est valable 2 ans.

      {:.fr-highlight}
      > ⚠️ En conséquence, un sportif qui a concouru en novembre 2024 pour les sports d'hiver et qui est devenu sportif de haut niveau à cette période n'apparaîtra dans l'API qu'à partir de juillet 2025. Un statut demandé à un instant T peut donc être différent à un instant T+ en fonction des mises à jour. Les informations obtenues sont représentatives de la situation connue par Sport Data Hub au moment de l’appel. 
    know_more_description: |+

  data:
    description: |+
      **Cette API délivre** : 
      - **le statut actuel du sportif ou de l'arbitre-juge** : actif ou inactif ;
      - **la catégorie du sportif** : espoir, relève, élite, senior, reconversion, collectif national, arbitre-juge ou parcours de performance fédéral ;
      - **les informations du club** : nom, localisation, affiliation ;
      - **l'historique du statut** : statuts précédents, catégories, clubs etc.. Les données historiques remontent à 1994 pour les listes ministerielles et à partir de 2012 pour les sportifs du Projet de performance fédéral (PPF). Ce n'est qu'à partir de 2017 que tous les sportifs du PPF ont été intégrés. 

  parameters_details:
    description: |+
      Cette API propose une modalité d'appel :

      <p class="fr-badge fr-badge--purple-glycine">Identifiant PSQS</p>
      **Avec l'identifiant PSQS** : Identifiant utilisé pour se connecter au portail de suivi quotidien du sportif (PSQS)
  provider_uids:
    - 'sport_data_hub'
  keywords:
    - 'Sportifs de haut niveau'
    - 'SHN'
    - 'Sportifs des collectifs nationaux'
    - 'SCN'
    - 'Sportifs espoirs'
    - 'SE'
    - 'Arbitres-juges de haut niveau'
    - 'AJSHN'
    - 'PSQS'
    - 'Sportifs'
    - 'Club sportif'
    - 'Elite'
    - 'Senior'
    - 'Releve'
    - 'Rconversion'
    - 'Espoir'
    - 'Sportifs en listes ministérielles'
    - 'PPF'
    - 'parcours de performance fédéral'

  faq:
    - q: "A quoi correspondent les différentes catégories de sportifs ?"
      a: |+
        Sportifs de haut niveau (SHN). Ils sont inscrits sur la Liste des Sportifs de Haut Niveau (SHN) publiée par le ministère, et sont répartis en plusieurs sous-catégories :
        Élite : Athlètes ayant obtenu des résultats exceptionnels au niveau international (Jeux Olympiques, Championnats du monde...).
        Sénior : Sportifs en équipe nationale avec un potentiel pour des compétitions internationales.
        Relève : Jeunes sportifs avec un fort potentiel pour accéder au plus haut niveau.
        Reconversion : |
          Anciens sportifs de haut niveau bénéficiant d’un accompagnement pour leur transition professionnelle.

          Sportifs Espoirs : Jeunes talents identifiés comme prometteurs par leur fédération, mais n’ayant pas encore atteint le niveau international.

          Sportifs des Collectifs Nationaux : Athlètes appartenant aux équipes nationales dans certaines disciplines spécifiques.

          Sportifs du parcours de performance fédéral : Le Parcours de Performance Fédéral (PPF) est un programme structuré permettant d’identifier et d’accompagner les jeunes talents jusqu’au haut niveau. Ces jeunes ne sont pas encore sur liste ministérielle.

          Arbitres et juges de haut niveau : Officiels qui assurent le bon déroulement des compétitions en appliquant les règles du sport concerné. Ils peuvent être :
          Arbitres (sports collectifs : football, basket, rugby, handball, etc.)
          Juges (sports notés : gymnastique, patinage, natation artistique, etc.)
          Officiels techniques (athlétisme, escrime, haltérophilie, etc.)

  api_cgu:
    description: |+
        Les conditions d'utilisations spécifiques à l'API
