
---
- uid: 'cnav/v2/allocation_soutien_familial'
  opening: protected
  new_endpoint_uids:
    - 'cnav/allocation_soutien_familial'
  path: '/api/v2/allocation-soutien-familial'
  swagger_version: 2
  ping_url: 'https://particulier.api.gouv.fr/api/caf/ping'
  position: 900
  perimeter:
    entity_type_description:
        ✅ Le périmètre de l’API est _a priori_ exhaustif et couvre tous les bénéficiaires de l'allocation de soutien familial (ASF).

        ⚙️ Vérification en cours avec le fournisseur de données pour confirmer le périmètre exact.
    geographical_scope_description: |+
      - ✅ France Métropolitaine
      - ✅ Départements d’Outre-mer
      - ❌ Les collectivités d’Outre-mer, ayant un autre système de sécurité sociale, ne sont pas concernées par cette API.
      - ⚙️ Personne de nationalité étrangère - Vérification en cours avec le fournisseur de la donnée pour confirmer la prise en charge. D'un point de vue métier, des prestations sont bien délivrées à une personne étrangère ayant un numéro d'immatriculation en attente (NIA) mais nous ne savons pas encore si le NIA est supporté par l'API.
    updating_rules_description:
      Les données sont **mises à jour en temps réel** et issues du répertoire national commun de la protection sociale (RNCPS) opéré par la CNAV (Caisse nationale d’assurance vieillesse). Les données du répertoire sont remontées directement par les différents organismes comme la CNAF pour les assurés du régime général et la MSA pour les assurés au régime agricole.
  parameters_details:
    description: |+
      Cette API propose deux modalités d'appel :
      <p class="fr-badge fr-badge--blue-ecume">![Cette API est FranceConnectée](<%= image_path('api_particulier/cas_usages/pictos/modalite_appel_france_connect.svg') %>){:width="20px"} FranceConnect</p>
      **Avec la [modalité d'appel FranceConnect](<%= cas_usage_path('modalite_appel_france_connect') %>)**.

      <p class="fr-badge fr-badge--brown-cafe-creme">Identité pivot</p>
      **Avec les données d'identité** : 
        
        {:.fr-mb-0}
        - Nom de naissance<sup>\*</sup>, nom d'usage, prénoms<sup>1</sup>, sexe<sup>\*</sup>, date de naissance de l'allocataire<sup>\**</sup>&nbsp;;
        - Lieu de naissance&nbsp;: 
            - *Si le lieu de naissance est en France,* la commune de naissance est obligatoire, elle peut être saisie de deux façons différentes :
                - {:.fr-text--sm .fr-mb-0} Option 1 : Code COG de la commune de naissance<sup>\*</sup>. [En savoir plus](#renseigner-lieu-de-naissance)&nbsp;;
                - {:.fr-text--sm .fr-mb-0} Option 2 : Nom de la commune de naissance<sup>\*</sup> et code du département de naissance<sup>\*</sup>. Pour cette option, la date de naissance est obligatoire. [En savoir plus](#renseigner-lieu-de-naissance).
                
              Pour chacune des deux options ci-dessus, le code COG de la France `99100`<sup>\*</sup> doit également être renseigné en paramètre d'appel. Vous n'avez pas besoin de le demander à l'usager, il peut être déduit de la commune de naissance.
            - *Si le lieu de naissance est à l'étranger&nbsp;:* code COG du pays de naissance<sup>\*</sup>.

      <span class="fr-text--xs">
      <sup>\*</sup> Obligatoire | <sup>\**</sup> Obligatoire pour l'option 2 du lieu de naissance.
      </span>
      <span class="fr-text--xs fr-m-0">
      <sup>1</sup> Fournir plusieurs prénoms permet de limiter les risques d'homonymie mais un seul prénom peut fonctionner. Attention, l'usager doit compléter chaque prénom dans un champ distinct.
      </span>

      {:.fr-highlight.fr-highlight--caution}
      > ⚠️ **Message API Particulier du 04.06.2024** : Nous avons constaté que les appels effectués sans nom de naissance et **avec le nom d'usage ne fonctionnent pas** dans une très grande partie des cas. Après investigation auprès de la CNAV (opérateur de l'API source), API Particulier a donc décidé de passer le paramètre "Nom de naissance" en obligatoire.
  data:
    description: |+
      Cette API **indique si le particulier est bénéficiaire de l'allocation de soutien familial**. En précisant :
        - la date d'ouverture du droit ;
        - la date de fermeture du droit.
  provider_uids:
    - 'cnav'
  keywords:
    - allocation
    - aides
    - famille
    - asf
  call_id: 
    - Identité pivot
    - FranceConnect
  parameters: 
    - Identité pivot
    - FranceConnect
  faq:
    - q: <a name="renseigner-lieu-de-naissance"></a> Appel avec l'identité pivot, comment renseigner le lieu de naissance ?
      a: |+
       Lorsque l'API est appelée avec l'identité pivot, pour identifier correctement le particulier, le système d'information a besoin de récupérer le lieu de naissance du particulier.

        - **Pour les particuliers nés en France**: le code COG pays `99100` est obigatoire. La commune de naissance est également obligatoire et peut-être renseignée via deux options différentes&nbsp;:

            - *Option 1 : L'API est appelée avec le code COG commune lui-même*. Pour aider les usagers à renseigner leur code COG, consultez la publication suivante :
              {:.fr-icon-arrow-right-line .fr-link--icon-right}
              [✒️ **Aider les usagers à renseigner leur lieu de naissance par code COG** - Lire la publication du 08/11/2023](https://particulier.api.gouv.fr/blog/parametre-lieu-naissance-code-cog){:target="_blank"}

            - *Option 2 : L'API est appelée avec le nom de la commune de naissance et le code du département de naissance*. La date de naissance est obligatoire car c'est elle qui permettra à l'API de faire la correspondance avec le bon code COG.
        
        - **Pour les particuliers nés à l'étranger**: le code COG pays est obigatoire.

        {:.fr-highlight}
        > **Le code COG du pays de naissance est obligatoire pour tous les appels.** Pour simplifier le parcours des usagers, évitez de demander aux particuliers nés en France de saisir leur pays de naissance, puisque vous pouvez le paramétrer directement -code COG pays France `99100`-, dès qu'un particuloer renseigne les informations de sa commune de naissance (forcément en France).
