---
- uid: 'dgfip/chiffres_affaires'
  path: '/v3/dgfip/etablissements/{siret}/chiffres_affaires'
  ping_url: 'https://entreprise.api.gouv.fr/ping/dgfip/chiffre_affaires'
  position: 210
  perimeter:
    entity_type_description: |+
      Seuls les chiffres d'affaires des **entreprises qui vérifient les deux conditions** suivantes, sont disponibles:
      - ✅ être **soumises à l'impôt sur les sociétés** selon les règles des régimes d'imposition réels, normal ou simplifié ;
      - ✅ avoir **transmis ses comptes annuels** aux greffes.

      ❌ Les entreprises aux régimes micro-BIC, micro-BNC et micro-BA (micro-entrepreneurs) ne sont pas concernées par cette API. En effet, elles ne sont pas soumises à l'impôt sur les sociétés mais relèvent de l’impôt sur le revenu.

    entities:
      - entreprises
  call_id: "SIREN"
  provider_uids:
    - 'dgfip'
  keywords:
    - 'finances'
    - 'financier'
    - 'résultat'
    - 'exercice'
    - 'marchés publics'
    - 'Aides publiques'
  data:
    description: |+
      Cette API retourne **jusqu'à trois exercices, les plus récents**.

      Ceux-ci ne sont pas forcément les exercices des trois dernières années car il peut y avoir plusieurs exercices dans une même année.
      Les exercices renvoyés sont listés les uns après les autres, le premier étant le plus récent des trois.

      Pour chaque exercice, le chiffre d’affaires en euros et la date de fin de l’exercice sont transmis.
  opening: protected
  format:
    - Donnée structurée JSON
  use_cases:
    - Marchés publics
    - Aides publiques
    - Détection de la fraude
  use_cases_optional:
    - Portail GRU - Instruction des démarches
  use_cases_forbidden:
    - Portail GRU - Préremplissage
    - Subventions associations
  parameters:
    - Numéro de SIREN de l'entreprise
  faq:
    - q: Quelle est la définition du chiffre d'affaires transmis ?
      a: |+
        **En régime réel normal**, le chiffres d'affaire correspond au montant porté en case FL du [formulaire 2052 - compte de résultat de l'exercice](https://www.impots.gouv.fr/portail/files/formulaires/2052-sd/2018/2052-sd_2117.pdf){:target="_blank"}, c'est-à-dire, le total des chiffres d'affaire nets de France et d'exportations et livraisons intracommunautaires.

        **En régime réel simplifié**, le chiffre d'affaires correspond à la somme des montants indiqués dans les cases 210, 214 et 218 du [formulaire 2033B - compte de résultat simplifié de l'exercice](https://www.impots.gouv.fr/portail/files/formulaires/2033-sd/2018/2033-sd_2094.pdf){:target="_blank"}, c'est-à-dire le total :
        - des ventes de marchandises (dont export et livraisons intracommunautaires) ;
        - de la production vendue des biens ;
        - de la production vendue des services, c'est-à-dire du montant des travaux, études et prestations de services exécutés, comprenant le cas échéant les produits des activités annexes (services exploités dans l'intérêt du personnel, commissions et courtages, locations diverses, mises à disposition de personnel facturées, ports et frais accessoires facturés, boni sur remises d'emballages consignés).

        [**Source : impôts.gouv**](https://www.impots.gouv.fr/portail/files/formulaires/2033-sd/2019/2033-sd_2570.pdf){:target="_blank"}
