---
- uid: "dgfip/liasses_fiscales"
  path: "/v3/dgfip/unites_legales/{siren}/liasses_fiscales/{year}"
  ping_url: "https://entreprise.api.gouv.fr/ping/dgfip/liasses_fiscales"
  position: 240
  perimeter:
    entity_type_description: |+
      Cette API délivre les liasses fiscales des entreprises :
      - ✅ soumises à l’impôt sur les sociétés (IS)* ;
      - ✅ soumises à l’impôt sur les sociétés dû par le groupe (IS GROUPE)*;
      - ✅ aux bénéfices industriels et commerciaux (BIC)* ;
      - ✅ aux bénéfices non commerciaux (BNC)* ;
      - ✅ aux bénéfices agricoles (BA)*.

      _*selon les règles des régimes réels, normal ou simplifié._

      ❌ **Les entreprises aux régimes micro-BIC, micro-BNC et micro-BA (micro-entrepreneurs) ne sont pas concernées par cette API**. En effet, elles ne déposent pas de déclarations de résultat mais des éléments spécifiques dans la déclaration 2042C qui relève de l’impôt sur le revenu.

    updating_rules_description: |+
      Les déclarations de résultat sont disponibles **à compter du lendemain de la date de dépôt (J+1) et trois jours plus tard (J+3)** si le dépôt intervient une veille de week-end.

      La date limite de dépôt des déclarations de résultat est fixée au 2ème jour ouvré après le 1er mai pour les entreprises qui clôturent à la fin de l’année civile.

      En cas d’exercice à cheval, la date limite de dépôt est positionnée exactement trois mois après la date de clôture de l’exercice déclaré.
    entities:
      - entreprises
  call_id: "SIREN"
  provider_uids:
    - "dgfip"
  keywords:
    - "finances"
    - "compte"
    - "financier"
    - "résultat"
    - "exercice"
    - "actif"
    - "passif"
    - "capital"
    - "valeur ajoutée"
    - "crédit"
    - "immobilisation"
    - "provision"
    - "participation"
    - "amortissement"
    - "créance"
    - "dette"
    - "déficit"
    - "plus-value"
    - "frais"
    - "adresse"
    - "imposition"
    - "régime"
    - "déclaration"
    - "fraude"
    - "imprime"
    - "effectif"
    - "déclarant"
    - "filiale"
    - "société-mère"
    - "participation"
  data:
    description: |+
      Cette API délivre **les liasses fiscales d'une entreprise** pour l'année renseignée. Elle ne permet pas d'accéder à tous les imprimés, mais seulement aux **imprimés utiles pour les démarches des marchés publics et aides publiques [listés ici](#faq_entry_0_api_entreprise_endpoint_dgfip_liasses_fiscales)**. 

      Pour chaque numéro d'imprimé, les règles d'imposition applicables à l'entreprise, ainsi que le millésime, la durée de l'exercice en jours et sa date de fin, ou encore la date de dépôt de la déclaration, sont transmis.

      **Les données présentes dans les imprimés sont variables et de différente nature**&nbsp;:
        - des **informations financières, fiscales et comptables** ;
        - des **données sur l'entreprise et son réseau** (filiale, société-mère, participation) dont les effectifs.
        - des **données de personnes**, nom, prénom, date et lieu de naissance, adresses postales, certaines rémunérations, etc.

  opening: protected
  format:
    - Donnée structurée JSON
  parameters:
    - Numéro de SIREN de l'entreprise
  faq:
    - q: Quels sont les imprimés renvoyés par cette API ? Pourquoi certains imprimés ne sont pas renvoyés ?
      a: |+
        Cette API a été conçue et négociée dans le cadre spécifique des marchés publics et des aides publiques. Par conséquence, et en accord avec la DGFIP, seule la liste ci-dessous des imprimés est disponible:

        * De 2050 à 2057
        * 2058C
        * 2059F et G
        * 2033A, B, C, D, F et G
        * 2058ABIS
        * 2058BBIS
        * 2058RG
        * de 2144 à 2150
        * 2151TER
        * 2153
        * 2154
        * 2035A, F et G
        * 2139A, B, C, D, et E
        * 2146BIS
        * 2147BIS 
        * 2139BIS

        <div class="fr-download fr-mb-1v">
          <p><strong>🔎 Pour avoir un aperçu exhaustif des données disponibles par imprimé</strong>, vous pouvez consulter ce document&nbsp;:<br>
            <a href="/files/api-entreprise_liasses_fiscales_liste-des-champs-par-imprime.xls" download class="fr-download__link">Télécharger la liste des données possibles par imprimé
              <span class="fr-download__detail">XLSX – 22 ko</span>
            </a>
          </p>
          <p class="fr-text--xs">Source : Document basé sur le [dictionnaire TDFC 2022 de la DGFIP](https://www.impots.gouv.fr/cahier-des-charges-edi-tdfc-0){:target="_blank"}</p>
        </div>
    - q: Comment distinguer l'imprimé rectificatif de l'initial ?
      a: |+
        Pour un même exercice, il y a parfois plusieurs fois le même imprimé : il s'agit de corrections qui ont été apportées par une déclaration ultérieure.

        Les déclarations dans la réponse JSON de l'API sont alors triées de l'imprimé le plus récent au plus ancien. Ainsi **le premier imprimé est toujours le plus récent**.


        {:.fr-highlight.fr-highlight--caution}
        > La date de déclaration ne vous permet donc pas de distinguer l'imprimé rectificatif de l'imprimé initial car les deux imprimés ont toujours la même date de déclaration. Celle-ci correspond à la date du correctif.
    - q: Pourquoi ais-je parfois des imprimés en double ?
      a: |+
        Dans le cas où une société fait partie d'un groupe IS (groupe de société soumis à un régime d'intégration fiscale sur l'Impôt sur les Sociétés), l'entreprise souscrit une déclaration de résultat pour elle-même et une autre en tant que membre du groupe. Dans ce cas, les imprimés peuvent être renvoyés en double.

