---
- uid: 'dgfip/attestations_fiscales'
  position: 250
  old_endpoint_uids:
    - 'dgfip/v3/attestations_fiscales'
  path: '/v4/dgfip/unites_legales/{siren}/attestation_fiscale'
  perimeter: &dgfip_attestation_perimeter
    entity_type_description: |+
      Cette API délivre uniquement les attestations fiscales aux **✅ entreprises assujettis à l'impôt sur les sociétés (IS) et à la TVA.**.

      **L'API ne permet pas de récupérer les attestations fiscales** :
      - ❌ des entreprises qui relèvent de l'impôt sur le revenu (IR), quelque soit leur régime d'imposition, BIC, BNC ou BA. **À partir du moment où l'entreprise est imposée à l'IR, son attestation fiscale ne peut être obtenue par cette API** : les micro-entreprises sont de fait toujours exclues du périmètre de cette API ;
      - ❌ des sociétés ayant été créées durant l'année en cours ;
      - ❌ des sociétés bénéficiant d’un plan de règlement, redressement, sauvegarde ou conciliation ainsi que les sociétés ayant formulé un recours contentieux assorti d’un sursis de paiement.

      {:.fr-highlight}
      Pour ces dernières entreprises, l'obtention d'une attestation fiscale est possible en transmettant le [formulaire n° 3666](https://www.impots.gouv.fr/formulaire/3666-sd/attestation-de-regularite-fiscale){:target="_blank"} à leur service des impôts des entreprises. Ces entreprises ne peuvent pas bénéficier du service en ligne disponible sur le site [www.impots.gouv.fr](www.impots.gouv.fr){:target="_blank"}, conformément au [bulletin officiel des impôts du 7 décembre 2016 référencé BOI-DJC-ARF-20161207](https://bofip.impots.gouv.fr/bofip/8485-PGP.html/identifiant%3DBOI-DJC-ARF-20161207){:target="_blank"}.

      {:.fr-highlight.fr-highlight--caution}
      > **⚠️ Cette API n'est pas fiable pour ❌ les sociétés "filles" appartenant à un groupe de société**. Avant de d'utiliser cette API, il est de votre ressort d'avoir vérifié que l'entreprise n'est pas une société fille. [En savoir plus](#faq_entry_4_endpoint_dgfip_attestations_fiscales)

      **Exceptions observées :**
      Suite à un retour utilisateur, nous observons que les attestations fiscales des **sociétés en nom collectif (SNC) ayant opté à l'IS** ne sont pas délivrées par cette API. Cette absence serait dûe au fait que le service des impôts en charge peut être le service des impôts des particuliers dans le cas d'un associé personne physique. Même si tous les associés sont des personnes morales, l'attestation ne sera pas accessible.
    know_more_description: |+
      - Le BOFIP expose les [dispositions juridiques communes de l'attestation de régularité](https://bofip.impots.gouv.fr/bofip/8485-PGP.html/identifiant=BOI-DJC-ARF-20220209){:target="_blank"} ;
      - Cette page d'[economie.gouv.fr](https://www.economie.gouv.fr/entreprises/impot-revenu-impot-societe-statut){:target="_blank"} dresse les types d'imposition possibles par statuts d'entreprise et vous permet de mieux comprendre le périmètre des entreprises concernées par cette API.
    entities:
      - entreprises
      - associations
  call_id: &dgfip_attestation_call_id "SIREN"
  opening: &dgfip_attestation_opening protected
  provider_uids: &dgfip_attestation_provider_uids
    - 'dgfip'
  keywords: &dgfip_attestation_keywords
    - 'conformité'
    - 'conforme'
    - 'obligations'
    - 'cotisations'
    - 'decret janvier 2019'
    - 'finances'
    - 'financier'
    - 'impôt'
    - 'TVA'
    - 'marchés publics'
    - 'Aides publiques'
    - 'fraude'
  data: &dgfip_attestation_data
    description: |+
      Cette API délivre l'attestation de régularité fiscale d'une entreprise, au format PDF. L'attestation est **délivrée ✅ si l'entreprise est en règle de ses obligations** déclaratives et de paiement d'IS et de TVA.

      La date de délivrance de l'attestation correspond au jour de l'appel et statue donc de la **situation de l'entreprise au dernier jour du moins M-1**. [En savoir plus sur la date de délivrance](#faq_entry_3_endpoint_dgfip_attestations_fiscales).

      <section class="fr-accordion">
        <h3 class="fr-accordion__title">
          <button class="fr-accordion__btn" aria-expanded="false" aria-controls="accordion-1">Liste des informations disponibles sur l'attestation</button>
        </h3>
        <div class="fr-collapse" id="accordion-1">

        - **Des informations sur l'entreprise&nbsp;:**
          - dénomination sociale de la société&nbsp;;
          - adresse de l'établissement principal&nbsp;;
          - numéro de SIREN&nbsp;;

        - **Un paragraphe listant les obligations fiscales en règle**&nbsp;;

        - **Des informations relatives à l'attestation&nbsp;:**
          - date de délivrance&nbsp;;
          - numéro de délivrance - 💡 _Grâce à API Entreprise vous n'avez pas besoin d'utiliser ce numéro pour vérifier l'authenticité des documents car toutes nos attestations sont issues directement de la DGFIP et donc certifiées !_
          - coordonnées du service des impôts gestionnaire.
        </div>
      </section>

      {:.fr-h6 .fr-mt-4w}
      ### Exemple d'attestation PDF&nbsp;:

      <div class="fr-download">
       <p>
        <a href="/files/exemple-dgfip-attestation-fiscale.pdf" download class="fr-download__link">
         Télécharger un exemple d'attestation fiscale
         <span class="fr-download__detail">
         PDF – 279 Ko
         </span>
        </a>
       </p>
      </div>
  format:
    - URL vers l'attestation en PDF
  use_cases: &dgfip_attestation_use_cases
    - Marchés publics
    - Aides publiques
    - Détection de la fraude
    - Portail GRU - Instruction des démarches
  use_cases_forbidden: &dgfip_attestation_use_cases_forbidden
    - Portail GRU - Préremplissage
    - Subventions associations
  parameters:  &dgfip_attestation_parameters
    - Numéro de SIREN de l'entreprise
  faq: &dgfip_attestation_faq
    - q: L’api ne renvoie pas de pièce, cela signifie-t'il que l’entreprise n’est pas à jour ?
      a: |+
        Non, dans certains cas particuliers, l'API ne peut pas renvoyer l’attestation.
        Cela ne veut pas dire que l’entreprise n’est pas à jour. Il faut se rapprocher de l’entreprise pour lui demander la pièce directement.

        De plus, si une entreprise se voit refuser la délivrance de l’attestation pour cause de carence de ses déclarations
        ou de ses paiements, cette non-délivrance n’est pas définitive pour toute l’année N.
        Si ensuite elle régularise sa situation pour les années N-1 et antérieures, alors l’attestation de régularité lui sera délivrée.



    - q: Quelles obligations fiscales sont prises en compte ?
      a: |+
        L'attestation prend en compte :
        * ✅ la taxe sur la valeur ajoutée (TVA) ;
        * ✅ l'impôt sur les sociétés (IS).

        L'attestation ne concerne pas :
        * ❌ la contribution économique territoriale (CET) ;
        * ❌ la cotisation foncière des entreprises (CFE) ;
        * ❌ la cotisation sur la valeur ajoutée des entreprises (CVAE) ;
        * ❌ la taxe sur les salaires (TS).

        Plus d'informations disponibles dans le [BOFIP - Dispositions juridiques communes - Attestation de régularité fiscale.](https://bofip.impots.gouv.fr/bofip/8485-PGP.html/identifiant%3DBOI-DJC-ARF-20161207){:target="_blank"}



    - q: L'attestation délivrée n'est pas signée, comment s'assurer de son authenticité ?
      a: |+
        L'attestation de régularité fiscale délivrée est une version dématérialisée. **Toutes les données délivrées par API Entreprise sont certifiées car prise à la source** ; dans ce cas précis, directement auprès de la DGFIP. Par ailleurs, le numéro de délivrance indiqué sur le PDF est unique et permet de s'assurer de l'authenticité du document.

        **Cette attestation à la même valeur juridique qu'une attestation signée par les services des impôts concernés**.

        Plus d'informations disponibles dans le [BOFIP - Dispositions juridiques communes - Attestation de régularité fiscale](https://bofip.impots.gouv.fr/bofip/8485-PGP.html/identifiant%3DBOI-DJC-ARF-20161207){:target="_blank"}.


    - q: Quelle est la date de délivrance de l'attestation ?
      a: |+
        D'après le [BOFIP - Alinéa 180](https://bofip.impots.gouv.fr/bofip/8485-PGP.html/identifiant=BOI-DJC-ARF-20220209){:target="_blank"}; l'attestation de régularité fiscale peut être obtenue tout au long de l'année et apprécie la situation de l'entreprise au dernier jour du mois précédant la demande de délivrance de l'attestation.

        La date de délivrance des attestations obtenues sur API Entreprise est la date de l'appel. Par conséquent, les attestations fiscales délivrées sur l'API Entreprise indiquent que l'entreprise était à jour de ses cotisations au dernier jour du mois M-1.

    - q: Pourquoi l'attestation délivrée par cette API n'est pas valable pour une entreprise filiale d'un groupe de sociétés ?
      a: |+
        Une société fille doit fournir deux attestations pour justifier de sa situation fiscale :
        * sa propre attestation, justifiant de ses propres obligations, à savoir le dépôt des déclarations de résultats et de TVA, ainsi que le paiement de la TVA ;
        * l'attestation de régularité fiscale de la société mère du groupe, qui confirme le paiement de l'impôt sur les société.

        Cette API ne permet pas d'entrer le numéro de SIREN de la société mère. Par conséquent, elle ne délivre que la partie concernant la société fille. Ce qui est insuffisant. En effet, il manquera les informations de la société "mère".

        **Il est de votre ressort de vérifier si l'entreprise est membre ou non d'un groupe de sociétés imposé selon le régime fiscal d'intégration visé à l'[article 223 A du CGI](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000042340402/){:target="_blank"} afin de ne pas utiliser une attestation qui ne serait pas valable.**

        Une API dédiée sera bientôt disponible.

        Plus d'informations disponibles dans le [BOFIP - Dispositions juridiques communes - Attestation de régularité fiscale](https://bofip.impots.gouv.fr/bofip/8485-PGP.html/identifiant%3DBOI-DJC-ARF-20161207){:target="_blank"}.
  historique: |+
    - Ajout de 2 champs dans la réponse: `date_delivrance_attestation` et `date_periode_analysee`
- uid: 'dgfip/v3/attestations_fiscales'
  position: 9002
  new_endpoint_uids:
    - 'dgfip/attestations_fiscales'
  path: '/v3/dgfip/unites_legales/{siren}/attestation_fiscale'
  perimeter: *dgfip_attestation_perimeter
  opening: *dgfip_attestation_opening
  call_id: *dgfip_attestation_call_id
  parameters: *dgfip_attestation_parameters
  format:
    - Payload JSON
  use_cases: *dgfip_attestation_use_cases
  use_cases_forbidden: *dgfip_attestation_use_cases_forbidden
  provider_uids: *dgfip_attestation_provider_uids
  keywords: *dgfip_attestation_keywords
  data: *dgfip_attestation_data
  faq: *dgfip_attestation_faq
