---
- uid: 'probtp/conformites_cotisations_retraite'
  path: '/v3/probtp/etablissements/{siret}/conformite_cotisations_retraite'
  position: 280
  perimeter:
    entity_type_description: |+
      Cette API concerne : 
      
      - ✅ Les entreprises **industrielles et artisanales du Bâtiment** ;
      - ✅ les entreprises des **Travaux Publics** ;
      - ✅ les entreprises des **Industries connexes** liées par les [Accords Collectifs Nationaux du 13 décembre 1990](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635897){:target="_blank"} et/ou du [13 novembre 1959](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635163/){:target="_blank"} ou organismes dont la demande d'adhésion a été acceptée dans les conditions prévues par l'[accord du 8 décembre 1961](https://www.agirc-arrco.fr/wp-content/uploads/2021/10/Accord_8dec1961.pdf){:target="_blank" et le règlement intérieur de l’institution soit :
          - la Confédération de l'Artisanat et des Petites Entreprises du Bâtiment (CAPEB) ;
          - la Fédération Française du Bâtiment (F.F.B) ;
          - la Fédération Française des Entreprises de Génie Électrique et Énergétique (F.F.I.E) ;
          - la Fédération des SCOP BTP ;
          - la Fédération Nationale des Travaux Publics (FNTP).

      ❌ **Les associations ne sont pas concernées.** 
    geographical_scope_description:
       Les entreprises adhérentes à ProBTP proviennent uniquement de la ✅ **France Corse métropolitaine**.
    updating_rules_description:
       L'information est vérifiée **tous les soirs** et l'API est connectée en temps réel au système de gestion de ProBTP. L'API délivre donc l'attestation telle qu'elle est connue des gestionnaires ProBTP.
    entities:
      - entreprises
  call_id: "SIRET"
  provider_uids:
    - 'probtp'
  keywords:
    - 'conformité'
    - 'conforme'
    - 'obligations'
    - 'cotisations'
    - 'btp'
    - 'bâtiment'
    - 'travaux'
    - 'marchés publics'
    - 'Aides publiques'
    - 'fraude'
  data:
    description: |+
      Cette API délivre l'attestation PROBTP d'une entreprise, au format PDF, lorsque cette dernière est à jour des cotisations indiquées sur l'attestation, dont les **cotisations de retraite complémentaire**.

      L'attestation explicite : 
      - les contrats retraite et prévoyance souscrits ;
      - la régularité de versement des cotisations, indiquée comme suit : « _En tenant compte des éléments connus à cette date, elle_ [l'entreprise] _est à jour des cotisations exigibles au JJ.MM.AAAA_ ».

      {:.fr-h6 .fr-mt-4w}
      ### Exemple d'attestation PDF&nbsp;:

      <div class="fr-download">                
       <p>                    
        <a href="/files/exemple-probtp-conformites_cotisations_retraite.pdf" download class="fr-download__link">
         Télécharger un exemple d'attestation ProBTP                       
         <span class="fr-download__detail">                            
         PDF – 276 Ko                                
         </span>                    
        </a>                
       </p>            
      </div> 
  opening: protected
  format:
    - Donnée structurée JSON
  use_cases:
    - Marchés publics
  use_cases_optional:
    - Aides publiques
    - Détection de la fraude
    - Portail GRU - Instruction des démarches
  use_cases_forbidden:
    - Portail GRU - Préremplissage
    - Subventions associations
  parameters:
    - Numéro de SIRET de l'établissement
