---
- uid: 'cnetp/attestations_cotisations_conges_payes_chomage_intemperies'
  ping_url: 'https://entreprise.api.gouv.fr/ping/cnetp/attestation_cotisations_conges_payes_chomage_intemperies'
  path: '/v3/cnetp/unites_legales/{siren}/attestation_cotisations_conges_payes_chomage_intemperies'
  position: 300
  perimeter:
    entity_type_description: |+
      Cette API couvre les **✅ entreprises cotisant à la caisse nationale pour les entrepreneurs de travaux publics (CNETP)** dont la particularité est d'exercer une ou plusieurs activités entrant dans le champ d'application des **conventions collectives nationales des Travaux Publics**. <a class=" fr-icon-arrow-down-line fr-link--icon-right" href="#conventions-collectives">Consulter les conventions concernées</a>.

      **❌ Ne sont pas concernées par cette API :**
      - les entreprises relevant des conventions collectives du bâitment qui dépendent de la caisse CIBTP. Pour accéder aux attestations de ces entreprises, veuillez consulter l'[API de la CIBTP](<%= endpoint_path(uid: 'cibtp/attestations_cotisations_conges_payes_chomage_intemperies') %>) ;
      - les entreprises qui règlent les cotisations dues à la CNETP au travers de l’URSSAF dans le cadre du Titre Emploi Service Entreprise (TESE) et dont le système d'information de la CNETP n'a pas l'attestation.
    geographical_scope_description: |+
      La caisse CNETP couvre les entreprises de :
      - ✅ Métropole
      - ✅ Guadeloupe, Guyane, Martinique, la Réunion.
    know_more_description: |+
      La CNETP est adhérente de la [CIBTP France (Réseau des Caisses de congés payés)](https://www.cibtp.fr){:target="_blank"} qui fédère l’ensemble des caisses de congés payés existant dans le Bâtiment et les Travaux Publics. La CNETP a reçu le mandat d’assurer, pour le compte de CIBTP France qui en a la responsabilité, l’indemnisation du chômage-intempéries et le recouvrement des cotisations correspondantes. Elle est donc légalement en charge du service des congés payés dans le secteur des Travaux Publics.

      **Liens utiles :**
      - le [site de la CNETP](https://www.cnetp.org/category/affiliation/){:target="_blank"} ;
      - l'[article D.3141-12 du code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000020572124/){:target="_blank"} qui définit les entreprises qui sont tenues d’adhérer auprès d'une caisse de congés payés du BTP.
    entities:
      - entreprises
  call_id: "SIREN"
  provider_uids:
    - 'cnetp'
  keywords:
    - 'conformité'
    - 'conforme'
    - 'obligations'
    - 'cotisations'
    - 'btp'
    - 'bâtiment'
    - 'travaux'
    - 'marchés publics'
    - 'Aides publiques'
    - 'fraude'
  data:
    description: |+
      Cette API permet d'obtenir au format PDF une attestation délivrée à l'entreprise sous réserve que celle-ci&nbsp; soit à jour de ses déclarations et du paiement de cotisations congés payés et chômage-intempéries.

      {:.fr-h6 .fr-mt-4w}
      ### Exemple d'attestation PDF&nbsp;:

      <div class="fr-download">
       <p>
        <a href="/files/exemple-cnetp-attestations_cotisations_conges_payes_chomage_intemperies.pdf" download class="fr-download__link">
         Télécharger un exemple d'attestation CNETP
         <span class="fr-download__detail">
         PDF – 653 Ko
         </span>
        </a>
       </p>
      </div>
  opening: protected
  format:
    - URL vers l'attestation en PDF
  parameters:
    - Numéro de SIREN de l'entreprise
  faq:
    - q: <a name="conventions-collectives"></a>Conventions collectives des entreprises concernées par cette API
      a: |+
        Cette API couvre les **entreprises dont la particularité est d'exercer une ou plusieurs activités entrant dans le champ d'application des conventions collectives nationales des Travaux Publics** :

        - ✅ [Convention collective nationale des ouvriers employés par les entreprises du bâtiment](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635221) visées par le décret du 1er mars 1962 (c’est-à-dire occupant jusqu’à 10 salariés) du 8 octobre 1990, étendue par arrêté du 12 février 1991 ;
        - ✅ [Convention collective nationale des ouvriers employés par les entreprises du bâtiment](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635220) non visées par le décret du 1er mars 1962 (c’est-à-dire occupant plus de 10 salariés) du 8 octobre 1990, étendue par arrêté du 8 février 1991 ;
        - ✅ [Convention collective nationale des employés, techniciens et agents de maîtrise du bâtiment](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000018773893) du 12 juillet 2006 ;
        - ✅ [Convention collective des cadres du bâtiment](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000017941839) du 1er juin 2004.
    - q: L'API ne renvoie pas de pièce, peut-on considérer que l'entreprise n'est pas à jour ?
      a: |+
        Non, dans certains cas nous ne pouvons pas récupérer l’attestation. Notamment, cette API ne permet de récupérer les attestations des entreprises réglant leurs cotisations à la CNETP au travers de l'URSSAF (dans le cadre du TESE).
