---
- uid: 'cnetp/attestations_cotisations_conges_payes_chomage_intemperies'
  ping_url: 'https://entreprise.api.gouv.fr/ping/cnetp/attestation_cotisations_conges_payes_chomage_intemperies'
  path: '/v3/cnetp/unites_legales/{siren}/attestation_cotisations_conges_payes_chomage_intemperies'
  position: 300
  perimeter:
    entity_type_description: |+
      Cette API couvre les **✅ entreprises cotisant à la caisse nationale pour les entrepreneurs de travaux publics (CNETP)** appartenant au réseau CIBTP France. Ces entreprises entrent dans le champ d'application des conventions collectives nationales du bâtiment et des travaux publics. <a class=" fr-icon-arrow-down-line fr-link--icon-right" href="#conventions-collectives">Consulter les conventions concernées</a>.

      **Ne sont pas concernées par cette API :**
      - ❌ les entreprises relevant des [autres caisses du réseau CIBTP France](#caisses-cibtp). Il est difficile d'anticiper si une entreprise du BTP cotise à la CNETP ou aux autres caisses de la CIBTP. Il est donc recommandé de faire un appel aux deux API systématiquement. Pour accéder aux certificats CIBTP, veuillez consulter [cette API](<%= endpoint_path(uid: 'cibtp/attestations_cotisations_conges_payes_chomage_intemperies') %>) ;
      - ❌ les entreprises qui règlent les cotisations dues à la CNETP au travers de l’URSSAF dans le cadre du Titre Emploi Service Entreprise (TESE) et dont le système d'information de la CNETP n'a pas l'attestation.

    know_more_description: |+
      - le [site de la CNETP](https://www.cnetp.org/category/affiliation/){:target="_blank"} ;
      - l'[article D.3141-12 du code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000020572124/){:target="_blank"} qui définit les entreprises qui sont tenues d’adhérer auprès d'une caisse de congés payés du BTP.
    entities:
      - entreprises
  call_id: "SIREN"
  provider_uids:
    - 'cnetp'
  keywords:
    - 'conformité'
    - 'conforme'
    - 'obligations'
    - 'cotisations'
    - 'btp'
    - 'bâtiment'
    - 'travaux'
    - 'marchés publics'
    - 'Aides publiques'
    - 'fraude'
  data:
    description: |+
      Cette API permet d'obtenir, au format PDF, le certificat délivré à l'entreprise sous réserve que son unité légale soit à jour de ses déclarations et du paiement de cotisations congés payés et chômage-intempéries.

      {:.fr-h6 .fr-mt-4w}
      ### Exemple d'attestation PDF&nbsp;:

      <div class="fr-download">
       <p>
        <a href="/files/exemple-cnetp-attestations_cotisations_conges_payes_chomage_intemperies.pdf" download class="fr-download__link">
         Télécharger un exemple d'attestation CNETP
         <span class="fr-download__detail">
         PDF – 653 Ko
         </span>
        </a>
       </p>
      </div>
  opening: protected
  format:
    - URL vers le certificat en PDF
  parameters:
    - Numéro de SIREN de l'entreprise
  faq:
    - q: <a name="caisses-cibtp"></a>Caisses de la CIBTP et distinction avec la CNETP
      a: |+
        **D'un point de vue du réseau**, l’Union des caisses de France CIBTP est composée de l’ensemble des caisses Congés Intempéries BTP, c'est-à-dire :
        - deux caisses nationales : la caisse nationale pour les entrepreneurs de travaux publics (CNETP) et la caisse nationale pour les sociétés coopératives de production du BTP ;
        - **des caisses métropolitaines** pour les entreprises du Bâtiment (une par région) ;
        - **de quatre caisses dans les départements d'Outremer** : Guadeloupe, Guyane, Martinique, la Réunion.

        L'ensemble des entreprises du BTP, environ 200 000, sont affiliées à une de ces caisses. 

        **D'un point de vue informatique**, toutes les caisses, à l'exception de la CNETP, transmettent leurs certificats à CIBTP France qui les redistribue au travers de [cette autre API](<%= endpoint_path(uid: 'cibtp/attestations_cotisations_conges_payes_chomage_intemperies') %>). Pour des raisons historiques, la CNETP gère elle-même ses certificats et propose donc cette API.

    - q: <a name="conventions-collectives"></a>Conventions collectives des entreprises concernées par cette API
      a: |+
        Cette API, comme [celle de la CIBTP](<%= endpoint_path(uid: 'cibtp/attestations_cotisations_conges_payes_chomage_intemperies') %>) couvre des **entreprises dont la particularité est d'exercer une ou plusieurs activités entrant dans le champ d'application des conventions collectives nationales du Bâtiment et des Travaux Publics** :

        - **Bâtiment :**
          - ✅ [Convention collective nationale des ouvriers employés par les entreprises du bâtiment](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635221) visées par le décret du 1er mars 1962 (c’est-à-dire occupant jusqu’à 10 salariés) du 8 octobre 1990, étendue par arrêté du 12 février 1991 ;
          - ✅ [Convention collective nationale des ouvriers employés par les entreprises du bâtiment](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635220) non visées par le décret du 1er mars 1962 (c’est-à-dire occupant plus de 10 salariés) du 8 octobre 1990, étendue par arrêté du 8 février 1991 ;
          - ✅ [Convention collective nationale des employés, techniciens et agents de maîtrise du bâtiment](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000018773893) du 12 juillet 2006 ;
          - ✅ [Convention collective des cadres du bâtiment](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000017941839) du 1er juin 2004.

        - **Travaux publics :**
          - ✅ [Convention collective nationale des ouvriers des travaux publics](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635467) du 15 décembre 1992, étendue par arrêté du 27 mai 1993 ;
          - ✅ [Convention collective nationale des employés, techniciens et agents de maîtrise des travaux publics](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000018926209) du 12 juillet 2006
          - ✅ [Convention collective nationale des cadres des travaux publics](https://www.legifrance.gouv.fr/conv_coll/id/KALISCTA000032426777/?idConteneur=KALICONT000032437525) du 20 novembre 2015.

    - q: L'API ne renvoie pas de pièce, peut-on considérer que l'entreprise n'est pas à jour ?
      a: |+
        Non, dans certains cas nous ne pouvons pas récupérer l’attestation. Notamment, cette API ne permet de récupérer les attestations des entreprises réglant leurs cotisations à la CNETP au travers de l'URSSAF (dans le cadre du TESE).
