---
- uid: 'opqibi/qualifications_ingenierie'
  path: '/v3/opqibi/unites_legales/{siren}/certification_ingenierie'
  ping_url: 'https://entreprise.api.gouv.fr/ping/opqibi/certification_ingenierie'
  position: 340
  perimeter:
    entity_type_description: |+
      ✅ **Toutes les unités légales certifiées par l'OPQIBI**, ce qui représente environ 2000 structures en 2020. Les entités éligibles à cette certification doivent impérativement avoir l'**ingénierie comme activité** principale ou accessoire. [En savoir plus sur les critères d'éligibilité](#faq_entry_0_endpoint_opqibi_qualifications_ingenierie).
    entities:
      - associations
      - entreprises
  call_id: "SIREN"
  provider_uids:
    - 'opqibi'
  keywords:
    - 'btp'
    - 'bâtiment'
    - 'travaux'
    - 'rénovation'
    - 'ingénierie'
    - 'capacité'
    - 'expertise'
    - 'technicité'
    - 'qualité'
    - 'marchés publics'
    - 'aides'
    - 'rge'
  data:
    description: |+
      Le certificat OPQIBI renseigne sur les capacités d'ingénierie d'une organisation. Il permet de connaître les qualifications et qualifications probatoires de l'entité. [En savoir plus](#faq_entry_1_endpoint_opqibi_qualifications_ingenierie).

      Cette API délivre :
      - les **informations relatives au certificat OPQIBI**, notamment les dates de délivrance et de validité ;
      - le **détail des qualifications**, dont notamment le code de la qualification, son libellé et sa définition, le statut “RGE Études" initié par l'ADEME s’il est reconnu, et les dates de validité.
      - l'**URL pour accéder au certificat en ligne**.

      <section class="fr-accordion">
        <h3 class="fr-accordion__title">
          <button class="fr-accordion__btn" aria-expanded="false" aria-controls="accordion-1">Liste des informations disponibles sur le certificat en ligne</button>
        </h3>
        <div class="fr-collapse" id="accordion-1">

        **Des informations sur l'entreprise&nbsp;:**

        - raison sociale, SIREN, SIRET, forme juridique, code NAF et capital social&nbsp;;
        - adresse du siège social et téléphone de l'entreprise&nbsp;;
        - e-mail et site internet&nbsp;;
        - communes des établissements secondaires&nbsp;;
        - nom, prénom et fonction du ou des dirigeants "ayant le pouvoir d'engager la structure"&nbsp;;
        - registre de commerce ou de répertoire des métiers auquel l'entreprise est rattachée&nbsp;;
        - numéro et ville d'enregistrement au registre du commerce&nbsp;;
        - assurances&nbsp;;
        - dernier chiffre d'affaires total connu, date indiquée&nbsp;;
        - dernier effectif.

        **Un tableau des qualifications attribuées&nbsp;:**
        - code&nbsp;;
        - libellé&nbsp;;
        - date d'effet.

        **Des informations liées au certificat&nbsp;:**

        - numéro d'identification du certificat&nbsp;;
        - date d'édition;nbsp;;
        - durée de validité.

        </div>
      </section>

  opening: public
  format:
    - Donnée structurée JSON et URL vers le certificat en ligne
  parameters:
    - Numéro de SIREN de l'unité légale.
  faq:
    - q: Quelle structure est éligible à une qualification OPQIBI ?
      a: |+
        Toute structure ayant l’ingénierie comme activité principale ou accessoire peut postuler à une qualification de l'OPQIBI :
        - qu'elle soit ou non adhérente à un syndicat professionnel,
        - qu'elle soit de création récente ou ancienne,
        - quelle que soit sa taille,
        - quelle que soit sa forme juridique
        - quel que soit son code d'activité,
        - qu'elle exerce des activités d'ingénierie à titre principal ou accessoire,
        - qu'elle soit indépendante ou filiale de structure privée ou publique,
        - qu'elle soit ou non issue d'une profession réglementée,
        - qu'elle soit française ou étrangère.

        **Source**: [Opqibi.fr](https://www.opqibi.com/page/qui-peut-se-faire-qualifier){:target="_blank"}

    - q: Qu'est-ce qu'une qualification ?
      a: |+
        Une **qualification atteste de la capacité** d’une entité d’ingénierie à réaliser une prestation déterminée. Elle est attribuée sur la base de critères légaux, administratifs, juridiques, financiers et techniques (moyens (humains, matériels, méthodologiques) et références).

        Une **qualification probatoire** est attribuée à une entité nouvellement créée ou en cours de diversification qui ne dispose pas encore de référence ou en nombre insuffisant mais satisfait aux critères légaux, administratifs, juridiques et moyens.

        La **mention « RGE »** (Reconnu Garant de l’Environnement) peut être délivrée aux professionnels réalisant des prestations intellectuelles concourant à la performance énergétique des bâtiments et des installations d’énergie renouvelable. [En savoir plus sur la reconnaissance RGE et l'OPQIBI](https://www.opqibi.com/page/qualifications-opqibi-et-reconnaissance-rge-etudes){:target="_blank"}.

        Une entité certifiée OPQIBI possède au moins une qualification ou une qualification probatoire.

    - q: Quelles durées de validité pour le certificat et les qualifications ?
      a: |+
        - Un certificat est valable 1 an ;
        - Une qualification est valable 4 ans sous réserve de 3 contrôles annuels ;
        - Une qualification probatoire est valable 1 an.

        **Source: [Opqibi.fr, rubrique "Validité et suivi"](https://www.opqibi.com/page/validite-et-suivi){:target="_blank"}.**

    - q: Certificat OPQIBI et commande publique
      a: |+
        Depuis mars 2019, les acheteurs publics sont mesure d'exiger « _des certificats de qualification professionnelle établis par des organismes indépendants_ » ([Arrêté du 22 mars 2019, article 3, alinéa 1-12°](https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000038320850){:target="_blank"}).

        **Source: [Opqibi.fr, rubrique "Certificats OPQIBI et marché publics"](https://www.opqibi.com/page/certificats-opqibi-et-marche-publics){:target="_blank"}.**
