---
- uid: 'qualifelec/certificats'
  path: '/v3/qualifelec/etablissements/{siret}/certificats'
  # Position au sein de l'index
  position: 1
  perimeter:
    entity_type_description: |+
      ✅ Toutes les **entreprises du génie électrique et énergétique** ayant obtenu une certification par [Qualifelec](https://www.qualifelec.fr/){:target="_blank"}. Toutes les certifications sont concernées : RGE ou non, accréditées ou non, probatoire ou classique.

      Cela représente environ 5000 établissements.
    geographical_scope_description:  |+
      - ✅ France métropolitaine
      - ✅ DROM COM
    updating_rules_description: |+
      Les données sont **mises à jour en temps réel**, l'API étant directement reliée au système d'information de Qualifelec.
    entities:
      - entreprises
  # Texte libre
  call_id: "SIRET"
  # La liste des clés disponible est stockée dans la locale `provider_uids` du fichier provider_uids.fr.yml
  provider_uids:
    - 'qualifelec'
  # Ces mots clés servent à la recherche algolia sur l'index du catalogue
  keywords:
    - 'qualifelec'
    - 'certificat'
    - 'capacite'
    - 'habilitation'
    - 'rge'
    - 'reconnu garant environnement'
    - 'energie'
    - 'electricite'
    - 'assurance'
    - 'decennale'
    - 'responsabilite civile'
    - 'mention'
    - 'classification'
    - 'qualification'
    - 'indice'
    - 'effectif'
  data:
    description: |+
      Cette API permet d'obtenir **la liste des certificats Qualifelec valides** obtenus par l'établissement. Pour chaque certificat, l'API délivre les données suivantes : 
      - **informations relatives au certificat** : numéro, dates de validité ; 
      - **informations sur la qualification obtenue** : labellisée RGE ou non, libellé, dates de validité, indices, mentions, domaines et la classification qui donne l'effectif du personnel d'execution et d'encadrement disponible pour cette qualification ;
      - **assurances décennale et de responsabilité civile** ;
      - l'url de téléchargement du certificat au **format PDF**.
     
      {:.fr-h6 .fr-mt-4w}
      ### Exemple de certificat PDF&nbsp;:

      <div class="fr-download">                
       <p>                    
        <a href="/files/exemple-certificat-qualifelec.pdf" download class="fr-download__link">
         Télécharger un exemple de certificat Qualifelec                      
         <span class="fr-download__detail">                            
         PDF – 756 Ko                               
         </span>                    
        </a>                
       </p>            
      </div>   
  opening: public
  use_cases_optional:
  use_cases_forbidden:
  use_cases:
    - Marchés publics
  parameters:
    - Numéro de SIRET de l'établissement
  format:
    - Donnée structurée JSON et document PDF
  faq:
    - q: "Question ?"
      a: |+
        Réponse à la question. Le markdown GFM est supporté ici.
  historique: |+
    **Ce que change la V.4 par rapport à la V.3 :**
    Texte

    **Ce qui ne change pas :**
    Texte
