---
- uid: 'insee/siege_social'
  path: '/v3/insee/sirene/unites_legales/{siren}/siege_social'
  ping_url: 'https://entreprise.api.gouv.fr/ping/insee/sirene'
  position: 135
  perimeter:
    entity_type_description: |+
      Cette API concerne les sièges sociaux des unités légales inscrites au répertoire Sirene :

      - ✅ les sièges sociaux des personnes morales de droit privé : **les entreprises et les entrepreneurs individuels**, dont toutes celles et ceux immatriculés au registre du commerce et des sociétés (RCS) et/ou au répertoire des métiers (RM) ;
      - ✅ les sièges sociaux **associations ayant un numéro de SIRET** délivré lorsqu'elles :
        * emploient du personnel salarié ;
        * sont soumises à la TVA ;
        * ont demandé ou bénéficient de transferts financiers publics.
      - ✅ les sièges sociaux des personnes morales de droit public : les **institutions et services de l'État** et les collectivités territoriales ;
      - ✅ Les sièges sociaux des organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.


      {:.fr-highlight}
      ✅ Depuis janvier 2022, les loueurs de meublés non professionnels (LMNP) et les particuliers employeurs, à l'exception des cas mentionnés au [2° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'être inscrits au répertoire Sirene. Cette modification intervient suite au [Décret n° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.


      ❌ Les établissements de gestion de paye de la fonction publique, bien que présents dans la base Sirene, ne sont pas concernés par cette API. Ils ont été immatriculés pour les seuls besoins de certaines administrations (les impôts, les URSSAF, la DGCP …).
      Leur diffusion à d'autres administrations n'est donc pas prévue.

    geographical_scope_description: &insee_siege_social_geographical_scope_description |+
      La base Sirene concerne les unités légales implantées en métropole, dans les DROM et dans les collectivités d'Outre-Mer de Saint-Pierre-et-Miquelon, Saint-Barthélémy et Saint-Martin.
      ⚠️ Pour la Nouvelle-Calédonie, la Polynésie française, et Wallis-et-Futuna, seul le secteur public administratif, de l'État ou des communes est répertorié ;
      ❌ les siègs sociaux des entreprises ne sont donc pas disponibles.

    updating_rules_description: &insee_siege_social_updating_rules_description |+
      La mise a jour des données est faite **quotidiennement entre 0h et 3h** à l'Insee.
    know_more_description: &insee_siege_social_know_more_description |+
      L'[article R123-220 du Code du commerce](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904){:target="_blank"} liste les entités tenues d'être inclues dans le répertoire Sirene par l'Insee.

      {:.fr-icon-arrow-right-line .fr-link--icon-right}
      [🦸 **Le futur des “non-diffusibles”** - Lire la publication du 14/12/2022](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles)

      {:.fr-icon-arrow-right-line .fr-link--icon-right}
      [✒️ **Inciter vos usagers à mettre à jour leurs informations dans le répertoire Sirene** - Lire la publication du 02/06/2023](https://entreprise.api.gouv.fr/blog/references-sites-modification-donnees)
    entities: &insee_siege_entities
    - entreprises
    - associations
  opening: protected
  call_id: &insee_siege_social_call_id SIREN
  parameters: &insee_siege_social_parameters
    - Numéro de SIREN de l'unité légale
  format: &insee_siege_social_format
    - Donnée structurée JSON
  provider_uids: &insee_siege_social_provider_uids
    - 'insee'
  keywords: &insee_siege_social_keywords
    - 'activité'
    - 'naf'
    - 'ape'
    - 'identité'
    - 'identification'
    - 'état'
    - 'effectif'
    - 'raison sociale'
    - 'nom'
    - 'numéro tva'
    - 'forme juridique'
    - 'localisation'
    - 'emplacement'
    - 'adresse'
    - 'commune'
    - 'région'
    - 'pays'
    - 'cedex'
    - 'cessation'
    - 'clôture'
    - 'création'
    - 'siège'
    - 'remplissage'
    - 'fraude'
    - 'aides'
    - 'marchés'
  data:
    description: &insee_siege_social_provider_uids_data_description |+
      Cette API délivre les **informations générales d'un siège social à partir du numéro de SIREN de son unité légale**.

      Les données protégées des sièges sociaux en ["diffusion partielle"](#faq_entry_2_endpoint_insee_siege_social) sont accessibles avec cette API.
  faq:
    - q: &insee_siege_social_provider_uids_faq_q1 À quoi correspondent les états administratifs ? Une unité légale peut-elle être en activité alors que tous ses établissements sont fermés ?
      a: &insee_siege_social_provider_uids_faq_a1 |+
        À gros trait, l'état administratif vous permet de vérifier si l'entreprise ou l'association est en activité. Il faut pour cela distinguer et vérifier l'état administratif de l'unité légale et celui de ses établissments.

        **État administratif de l'unité légale&nbsp;:**
        L'état administratif de l'unité légale peut être "actif" ou "cessé".
        L'unité légale est toujours active, sauf si une déclaration de cessation administrative a été déposée et prise en compte par l'Insee.
        L'état administratif indique si une unité légale est active ou cessée.

        **État administratif d'un établissement&nbsp;:**
        Il peut être "actif" ou "fermé". Lors de son inscription au répertoire Sirene, un établissement est, sauf exception, à l'état "actif". Le passage à l'état "fermé" découle de la prise en compte d'une déclaration de fermeture. Un établissement fermé peut être rouvert.

        **Cas particuliers&nbsp;:**
        - **une unité légale est active alors que tous ses établissements sont fermés**. Il s'agit alors d'une entité active d'un point de vue administratif mais n'ayant pas d'activité économique. Cette situation regroupe :
           - Les sociétés en sommeil, c'est-à-dire faire reconnaître par une formalité leur état en sommeil afin de ne plus avoir certaines obligations fiscales ;
           - Les sociétés présumées inactives, identifiées par l’Insee pour des besoins statistiques.

           La distinction "en sommeil" ou "présumée inactive" n'est pas une information transmise par l'Insee.
        - **une unité légale est cessée alors qu'un établissement est actif**. Cette situation est une erreur à signaler au pôle du répertoire Sirene à l'Insee. Une unité légale cessée ne peut avoir d'établissements actifs.

    - q: &insee_siege_social_provider_uids_faq_q2 "L'état administratif du siège social est fermé mais l'unité légale est active, est-ce une erreur ?"
      a: &insee_siege_social_provider_uids_faq_a2 |+
        Même si tous les établissements d'une entreprise sont fermés, y compris son établissement siège, **une unité légale reste active tant que la cessation juridique n'a pas été prononcée**.

        Une réactivation est même encore possible. Le SIREN de l'unité légale continue donc d'avoir un statut "actif" au répertoire."

    - q: &insee_siege_social_provider_uids_faq_q3 Qu'est-ce qu'un siège social "en diffusion partielle" ?
      a: &insee_siege_social_provider_uids_faq_a3 |+
        **La diffusion partielle commerciale :**

        Parmi les entités présentes dans le répertoire Sirene, certaines, très majoritairement des personnes physiques, ont explicitement demandé de ne pas figurer en diffusion totale, afin de ne pas rendre publiques leurs données d'identification et de localisation.

        Ce [droit d'opposition tel que décrit à l'Article 21 du RGPD](https://www.cnil.fr/fr/reglement-europeen-protection-donnees/chapitre3#Article21){:target="_blank"} est valable pour les personnes physiques et morales mais s'applique de façon différente : 
        - pour les personnes morale, seuls les éléments de localisation sont protégés (géolocalisation, numéro et voie de l'adresse postale - la commune reste diffusible) ; 
        - pour les personnes physiques, les éléments de localisation précédents sont protégés, ainsi que les éléments d'identification (nom, prénom, pseudonyme).

        **Ces données protégées sont alors uniquement accessibles à des organismes habilités et à des administrations.** Elles sont disponibles dans l'API Entreprise.

        {:.fr-highlight}
        > Le statut de diffusion partielle est nouveau, il est venu remplacer le statut “non-diffusible” en 2023. Ce nouveau statut rend public plus d'informations, dont, pour les personnes physiques, le SIREN, SIRET, la commune et le pays, ainsi que l'état administratif et les variables économiques. Il a élargi la possibilité de la diffusion partielle aux personnes morales, pour leur permettre de cacher leurs données de localisation.<br>Lire notre publication du 14/12/2022 : [🦸&nbsp;**Le futur des “non-diffusibles”**](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles).


        **La non-diffusion totale disponibles pour des cas spécifiques :**
        Certaines entités ne sont pas diffusibles pour d'autres raisons que la non-diffusion commerciale. C'est par exemple le cas :
        - des établissements de gestion de paye de la fonction publique immatriculés pour les seuls besoins de certaines administrations (les impôts, les URSSAF, la DGCP …) et donc uniquement accessibles à ces administrations fiscales.
        - des unités de la Défense nationale, accessibles sur autorisation du Ministère de la Défense, conformément à l’[article A 123-95 du Code du commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000020165032/2010-07-02){:target="_blank"}. **Ces unités ne sont pas diffusées par l'API Entreprise**.

    - q: &insee_siege_social_provider_uids_faq_q4 des sièges sociaux "en diffusion partielle" ?
      a: &insee_siege_social_provider_uids_faq_a4 |+
        En utilisant cette API, vous vous engagez à **tenir compte du statut de diffusion le plus récent** de l'entité appelée.
        Dans le cas où l'entité est indiquée comme \"en diffusion partielle\", vous vous engagez à n'utiliser leurs informations protégées que dans le cadre strict de vos missions de service public, à ne pas les rediffuser ni les divulguer auprès de tiers non autorisés.

        {:.fr-highlight.fr-highlight--caution}
        > ⚠️ **Vous ne pouvez pas donc pas faire usage des données protégées d'une entité "en diffusion partielle" pour du préremplissage.** Seules les données diffusibles peuvent être utilisées pour du préremplissage, c'est-à-dire : le SIREN, SIRET, la commune et le pays, ainsi que l'état administratif et les variables économiques.
        > Pour faire du pré-remplissage dans un formulaire public, nous vous recommandons d'utiliser l'[API délivrant uniquement de l'open data](<%= endpoint_path(uid: 'insee/siege_social_diffusibles') pour ne pas faire d'erreur.

        {:.fr-highlight}
        > **Depuis 2023, les personnes morales sont concernées par la \"diffusion partielle\"**. Si elles ont exercé ce droit, vous n'avez pas le droit de pré-remplir leur données de localisation : géolocalisation, numéro et voie de l'adresse postale. La commune reste diffusible.

- uid: 'insee/siege_social_diffusibles'
  path: '/v3/insee/sirene/unites_legales/diffusibles/{siren}/siege_social'
  ping_url: 'https://entreprise.api.gouv.fr/ping/insee/sirene'
  position: 130
  perimeter:
    entity_type_description: |+
      Cette API concerne les sièges sociaux des unités légales inscrites au répertoire Sirene et **"diffusibles" commercialement** :
      - ✅ les sièges sociaux des personnes morales de droit privé : **les entreprises et les entrepreneurs individuels**, dont toutes celles et ceux immatriculés au registre du commerce et des sociétés (RCS) et/ou au répertoire des métiers (RM) ;
      - ✅ les sièges sociaux **associations ayant un numéro de SIRET** délivré lorsqu'elles :
        * emploient du personnel salarié ;
        * sont soumises à la TVA ;
        * ont demandé ou bénéficient de transferts financiers publics.
      - ✅ les sièges sociaux des personnes morales de droit public : les **institutions et services de l'État** et les collectivités territoriales ;
      - ✅ Les sièges sociaux des organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.


      {:.fr-highlight}
      ✅ Depuis janvier 2022, les loueurs de meublés non professionnels (LMNP) et les particuliers employeurs, à l'exception des cas mentionnés au [2° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'être inscrits au répertoire Sirene. Cette modification intervient suite au [Décret n° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.

      ❌ **Pour les sièges sociaux ["en diffusion partielle"](#faq_entry_2_endpoint_insee_siege_social_diffusibles), seules leurs données publiques sont disponibles avec cette API**, leurs informations protégées sont appelables avec [cette API](<%= endpoint_path(uid: 'insee/siege_social') %>).

    geographical_scope_description: *insee_siege_social_geographical_scope_description
    updating_rules_description: *insee_siege_social_updating_rules_description
    know_more_description: *insee_siege_social_know_more_description
    entities: *insee_siege_entities
  opening: public
  format: *insee_siege_social_format
  parameters: *insee_siege_social_parameters
  call_id: *insee_siege_social_call_id
  provider_uids: *insee_siege_social_provider_uids
  keywords: *insee_siege_social_keywords
  data:
    description: *insee_siege_social_provider_uids_data_description
  faq:
    - q: *insee_siege_social_provider_uids_faq_q1
      a: *insee_siege_social_provider_uids_faq_a1
    - q: *insee_siege_social_provider_uids_faq_q2
      a: *insee_siege_social_provider_uids_faq_a2
    - q: *insee_siege_social_provider_uids_faq_q3
      a: *insee_siege_social_provider_uids_faq_a3
    - q: *insee_siege_social_provider_uids_faq_q4
      a: *insee_siege_social_provider_uids_faq_a4
