---
- uid: 'insee/unites_legales'
  path: '/v3/insee/sirene/unites_legales/{siren}'
  position: 125
  ping_url: 'https://entreprise.api.gouv.fr/ping/insee/sirene'
  perimeter:
    entity_type_description: |+
      Cette API concerne les unités légales inscrites au répertoire Sirene, qu'elles soient **"diffusibles" ou ["non-diffusibles"](#faq_entry_3_endpoint_insee_unites_legales)** :

      - ✅ les personnes morales de droit privé : les **entreprises** dont toutes celles immatriculées au registre du commerce et des sociétés (RCS) et au répertoire des métiers (RM) figurent dans la base Sirene ;
      - ✅ les **associations ayant un numéro de SIREN**, délivré lorsqu'elles :
        * emploient du personnel salarié ;
        * sont soumises à la TVA ;
        * ont demandé ou bénéficient de transferts financiers publics.
      - ✅ les personnes morales de droit public : les **institutions et services de l'État** et les collectivités territoriales ;
      - ✅ Les organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.

      {:.fr-highlight}
      ✅ Depuis janvier 2022, les loueurs de meublés non professionnels (LMNP) et les particuliers employeurs, à l'exception des cas mentionnés au [2° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'être inscrits au répertoire Sirene. Cette modification intervient suite au [Décret n° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.

      ❌ Les établissements de gestion de paye de la fonction publique, bien que présents dans la base Sirene, ne sont pas concernés par cette API. Ils ont été immatriculés pour les seuls besoins de certaines administrations (les impôts, les URSSAF, la DGCP …).
      Leur diffusion à d'autres administrations n'est donc pas prévue.

    geographical_scope_description: &insee_unites_legales_geographical_scope_description |+
      La base Sirene concerne les unités implantées en métropole, dans les DROM et dans les collectivités d'Outre-Mer de Saint-Pierre-et-Miquelon, Saint-Barthélémy et Saint-Martin.

      ⚠️ Pour la Nouvelle-Calédonie, la Polynésie française, et Wallis-et-Futuna, seul le secteur public administratif, de l'État ou des communes est répertorié ;
      ❌ les entreprises ne sont donc pas disponibles.

    updating_rules_description: &insee_unites_legales_updating_rules_description |+
      La mise a jour des données est **faite quotidiennement entre 0h et 3h** à l'INSEE.

    know_more_description: &insee_unites_legales_know_more_description |+
      L'[article R123-220 du Code du commerce](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904){:target="_blank"} liste les entités tenues d'être inclues dans le répertoire Sirene par l'Insee.

      {:.fr-icon-arrow-right-line .fr-link--icon-right}
      [🦸 **Le futur des “non-diffusibles”** - Lire la publication du 14/12/2022](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles)

      {:.fr-icon-arrow-right-line .fr-link--icon-right}
      [✒️ **Inciter vos usagers à mettre à jour leurs informations dans le répertoire Sirene** - Lire la publication du 02/06/2023](https://entreprise.api.gouv.fr/blog/references-sites-modification-donnees)
    entities:
      - entreprises
      - associations
  opening: protected
  call_id: &insee_unites_legales_call_id SIREN
  parameters: &insee_unites_legales_parameters
    - Numéro de SIREN de l'unité légale
  format: &insee_unites_legales_format
    - Donnée structurée JSON
  use_cases_optional:
    - Marchés publics
    - Aides publiques
    - Détection de la fraude
    - Portail GRU - Instruction des démarches
    - Subventions associations
  use_cases_forbidden:
    - Portail GRU - Préremplissage
  provider_uids: &insee_unites_legales_provider_uids
    - 'insee'
  keywords: &insee_unites_legales_keywords
    - 'activité'
    - 'naf'
    - 'ape'
    - 'identité'
    - 'identification'
    - 'état'
    - 'effectif'
    - 'raison sociale'
    - 'nom'
    - 'forme juridique'
    - 'cessation'
    - 'clôture'
    - 'création'
    - 'remplissage'
    - 'fraude'
    - 'aides'
    - 'marchés'
    - 'ess'
    - 'économie sociale et solidaire'
  data:
    description: &insee_unites_legales_data_description |+
      Cette API délivre **uniquement les informations de référence des unités légales**.

      Pour obtenir :
      - les informations des établissements, utilisez [cette API pour les "diffusibles"](<%= endpoint_path(uid: 'insee/etablissements') %>) et [cette API pour tous les établissements, y compris les "non-diffusibles"](<%= endpoint_path(uid: 'insee/etablissements_diffusibles') %>) ;
      - l'adresse des établissements, [cette API pour les "diffusibles"](<%= endpoint_path(uid: 'insee/adresse_etablissements_diffusibles') %>) et [cette API pour tous les établissements, y compris les "non-diffusibles"](<%= endpoint_path(uid: 'insee/adresse_etablissements') %>) ;
      - les mandataires sociaux, [cette API](<%= endpoint_path(uid: 'infogreffe/mandataires_sociaux') %>) .
      - les informations du siège social, [cette API pour les "diffusibles"](<%= endpoint_path(uid: 'insee/siege_social_diffusibles') %>) et [cette API pour tous les sièges sociaux, y compris les "non-diffusibles"](<%= endpoint_path(uid: 'insee/siege_social') %>).
  faq:
    - q: &insee_unites_legales_faq_q1 À quoi correspondent les états administratifs ? Une unité légale peut-elle être en activité alors que tous ses établissements sont fermés ?
      a: &insee_unites_legales_faq_a1 |+
        À gros trait, l'état administratif vous permet de vérifier si l'entreprise ou l'association est en activité. Il faut pour cela distinguer et vérifier l'état administratif de l'unité légale et celui de ses établissments.

        **État administratif de l'unité légale&nbsp;:**
        L'état administratif de l'unité légale peut être "actif" ou "cessé".
        L'unité légale est toujours active, sauf si une déclaration de cessation administrative a été déposée et prise en compte par l'Insee.
        L'état administratif indique si une unité légale est active ou cessée.

        **État administratif d'un établissement&nbsp;:**
        Il peut être "actif" ou "fermé". Lors de son inscription au répertoire Sirene, un établissement est, sauf exception, à l'état "actif". Le passage à l'état "fermé" découle de la prise en compte d'une déclaration de fermeture. Un établissement fermé peut être rouvert.

        **Cas particuliers&nbsp;:**
        - **une unité légale est active alors que tous ses établissements sont fermés**. Il s'agit alors d'une entité active d'un point de vue administratif mais n'ayant pas d'activité économique. Cette situation regroupe :
           - Les sociétés en sommeil, c'est-à-dire faire reconnaître par une formalité leur état en sommeil afin de ne plus avoir certaines obligations fiscales ;
           - Les sociétés présumées inactives, identifiées par l’Insee pour des besoins statistiques.

           La distinction "en sommeil" ou "présumée inactive" n'est pas une information transmise par l'Insee.
        - **une unité légale est cessée alors qu'un établissement est actif**. Cette situation est une erreur à signaler au pôle du répertoire Sirene à l'Insee. Une unité légale cessée ne peut avoir d'établissements actifs.

    - q: &insee_unites_legales_faq_q2 Une unité légale semble être successivement active puis cessée puis active, est-ce normal ?
      a: &insee_unites_legales_faq_a2 |+
        **Pour les personnes physiques**, dans le cas où l'exploitant déclare la cessation de son activité, puis la reprend quelque temps plus tard, **l'état administratif est réversible**. Il est donc normal d'avoir des périodes successives d'état actif puis cessé pour les personnes physiques.

        En revanche, **pour les personnes morales, l'état administratif est en théorie irréversible**.


    - q: &insee_unites_legales_faq_q3 Une unité légale est active mais tous ses établissements sont fermés, est-ce une erreur ?
      a: &insee_unites_legales_faq_a3 |+
        Même si tous les établissements d'une unité légale sont fermés, y compris son établissement siège, **une unité légale reste active tant que la cessation juridique n'a pas été prononcée.

        Une réactivation est même encore possible. Le SIREN continue donc d'avoir un statut "actif" au répertoire.


    - q: &insee_unites_legales_faq_q4 Qu'est-ce qu'un "non-diffusible" ?
      a: &insee_unites_legales_faq_a4 |+
        **La non-diffusion commerciale :**
        Parmi les entités présentes dans le répertoire Sirene, certaines, très majoritairement des personnes physiques, ont explicitement demandé de ne pas figurer en diffusion commerciale, en vertu de l'[article A123-96 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031043097/){:target="_blank"}.

        Cela signifie qu'elles donnent accord de la diffusion de leur données uniquement à des organismes habilités et à des administrations. **De fait, leurs données ne sont pas publiques**.

        {:.fr-highlight}
        > À partir de mars 2024, le fonctionnement des non-diffusibles commerciaux évolue, certaines données seront disponibles pour du pré-remplissage et les personnes morales pourront décider de passer en diffusion partielle. <br>Lire notre publication du 14/12/2022 : [🦸&nbsp;**Le futur des “non-diffusibles”**](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles).


        **La non-diffusion pour d'autres raisons :**
        Certaines entités ne sont pas diffusibles pour d'autres raisons que la non-diffusion commerciale. C'est par exemple le cas :
        - des établissements de gestion de paye de la fonction publique immatriculés pour les seuls besoins de certaines administrations (les impôts, les URSSAF, la DGCP …) et donc uniquement accessibles à ces administrations fiscales.
        - des unités de la Défense nationale, accessibles sur autorisation du Ministère de la Défense, conformément à l’[article A 123-95 du Code du commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000020165032/2010-07-02){:target="_blank"}. **Ces unités ne sont pas diffusées par l'API Entreprise**.



    - q: Comment utiliser les informations des unités légales "non-diffusibles" ?
      a: |+
        En utilisant cette API, vous vous engagez à **tenir compte du statut de diffusion le plus récent** de l'entité appelée.
        Dans le cas où l'entité est indiquée comme "non-diffusible", vous vous engagez à n'utiliser leurs informations que dans le cadre strict de vos missions de service public, à ne pas les rediffuser ni les divulguer auprès de tiers non autorisés.

        {:.fr-highlight.fr-highlight--caution}
        > ⚠️ **Vous ne pouvez pas donc pas faire usage des données d'une entité "non-diffusible" pour du préremplissage.**

        {:.fr-highlight}
        > Il vous est par contre possible d'indiquer à l'unité légale "non-diffusible" qu'elle peut modifier son statut, même provisoirement, auprès de l'Insee à l'adresse suivante : [https://statut-diffusion-sirene.insee.fr](https://statut-diffusion-sirene.insee.fr}{:target="_blank"}).

        À partir de mars 2024, le fonctionnement des non-diffusibles commerciaux évolue, certaines données seront disponibles pour du pré-remplissage et les personnes morales pourront décider de passer en diffusion partielle. Lire notre publication du 14/12/2022 : [🦸&nbsp;**Le futur des “non-diffusibles”**](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles).

    - q: &insee_unites_legales_faq_q6 Le numéro de TVA intracommunataire disponible en V.2.n'est plus disponible en V.3, où puis-je le trouver ?
      a: &insee_unites_legales_faq_a6 |+
        Lors de la conception de la V.3 de l'API Entreprise, nous avons décidé de ne plus délivrer le numéro de TVA intracommunautaire par le biais de l'API de l'Insee car cette donnée ne provient pas de ce fournisseur. Cette donnée était et est calculée par l'API Entreprise à partir du numéro de SIREN.

        **Une [API spécifique est maintenant disponible en V.3](<%= endpoint_path(uid: 'commission_europeenne/numero_tva') %>)** et permet de connaître le numéro intracommunautaire français d'une unité légale. Cette API effectue une vérification auprès du service compétent de la Commission européenne.

- uid: 'insee/unites_legales_diffusibles'
  path: '/v3/insee/sirene/unites_legales/diffusibles/{siren}'
  position: 120
  ping_url: 'https://entreprise.api.gouv.fr/ping/insee/sirene'
  perimeter:
    entity_type_description: |+
      Cette API concerne les unités légales inscrites au répertoire Sirene et **"diffusibles" commercialement** :
      - ✅ les personnes morales de droit privé : les **entreprises**, dont toutes celles immatriculées au registre du commerce et des sociétés (RCS) et au répertoire des métiers (RM) figurent dans la base Sirene ;
      - ✅ les **associations ayant un numéro de SIREN**, délivré lorsqu'elles :
        * emploient du personnel salarié ;
        * sont soumises à la TVA ;
        * ont demandé ou bénéficient de transferts financiers publics.
      - ✅ les personnes morales de droit public : les **institutions et services de l'État** et les collectivités territoriales ;
      - ✅ Les organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.

      {:.fr-highlight}
      ✅ Depuis janvier 2022, les loueurs de meublés non professionnels (LMNP) et les particuliers employeurs, à l'exception des cas mentionnés au [2° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'être inscrits au répertoire Sirene. Cette modification intervient suite au [Décret n° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.

      ❌ **Les unités légales ["non-diffusibles"](#faq_entry_3_endpoint_insee_unites_legales_diffusibles) ne sont pas concernées par cette API**, leurs informations sont appelables avec [cette API](<%= endpoint_path(uid: 'insee/unites_legales') %>).

    geographical_scope_description: *insee_unites_legales_geographical_scope_description
    updating_rules_description: *insee_unites_legales_updating_rules_description
    know_more_description: *insee_unites_legales_know_more_description
    entities:
    - entreprises
    - associations
  opening: public
  format: *insee_unites_legales_format
  use_cases_optional:
    - Détection de la fraude
    - Marchés publics
    - Aides publiques
    - Portail GRU - Préremplissage
    - Portail GRU - Instruction des démarches
    - Subventions associations
  parameters: *insee_unites_legales_parameters
  call_id: *insee_unites_legales_call_id
  provider_uids: *insee_unites_legales_provider_uids
  keywords: *insee_unites_legales_keywords
  data:
    description: *insee_unites_legales_data_description
  faq:
    - q: *insee_unites_legales_faq_q1
      a: *insee_unites_legales_faq_a1
    - q: *insee_unites_legales_faq_q2
      a: *insee_unites_legales_faq_a2
    - q: *insee_unites_legales_faq_q3
      a: *insee_unites_legales_faq_a3
    - q: *insee_unites_legales_faq_q4
      a: *insee_unites_legales_faq_a4
    - q: *insee_unites_legales_faq_q6
      a: *insee_unites_legales_faq_a6
