---
- uid: 'inpi/rne/actes_bilans'
  path: '/v3/inpi/rne/unites_legales/open_data/{siren}/actes_bilans'
  ping_url: 'https://entreprise.api.gouv.fr/ping/inpi/rne'
  position: 113
  perimeter:
    entity_type_description: |+
      Lorem
    geographical_scope_description:  |+
      - Lorem
    updating_rules_description: |+
      Lorem
    entities:
      - entreprises
  call_id: "SIREN"
  provider_uids:
    - 'inpi'
  keywords:
    - 'Lorem'
  data:
    description: |+
      Lorem Ipsum
  opening: 'Lorem'
  parameters:
    - Numéro de SIREN de l'unité légale
  format:
    - Donnée structurée JSON
