---
- uid: 'carif_oref/certifications_qualiopi_france_competences'
  path: '/v3/carif_oref/certifications_qualiopi_france_competences/{siret}'
  # Position au sein de l'index
  position: 1
  perimeter:
    entity_type_description: |+
      LOREM IPSUM

    geographical_scope_description:  |+
      - ✅ France métropolitaine
    updating_rules_description: |+
      LOREM IPSUM
    entities:
      - entreprises
  # Texte libre
  call_id: "SIRET"
  # La liste des clés disponible est stockée dans la locale `provider_uids` du fichier provider_uids.fr.yml
  provider_uids:
    - 'carif_oref'
  # Ces mots clés servent à la recherche algolia sur l'index du catalogue
  keywords:
    - 'LOREM'
    - 'IPSUM'
  data:
    description: |+
      lorem ipsum lalala
  opening: public
  use_cases_optional:
  use_cases_forbidden:
  use_cases:
    - Lorem
  parameters:
    - Siret de l'établissement
  format:
    - Donnée structurée JSON
