---
- uid: 'carif_oref/certifications_qualiopi_france_competences'
  path: '/v3/carif_oref/certifications_qualiopi_france_competences/{siret}'
  # Position au sein de l'index
  position: 1
  perimeter:
    entity_type_description: |+
      LOREM IPSUM

    geographical_scope_description:  |+
      - ✅ France métropolitaine
    updating_rules_description: |+
      LOREM IPSUM
    entities:
      - entreprises
  # Texte libre
  call_id: "SIRET"
  # La liste des clés disponible est stockée dans la locale `provider_uids` du fichier provider_uids.fr.yml
  provider_uids:
    - 'carif_oref'
  # Ces mots clés servent à la recherche algolia sur l'index du catalogue
  keywords:
    - 'LOREM'
    - 'IPSUM'
  data:
    description: |+
      lorem ipsum lalala
  opening: public
  use_cases_optional:
  use_cases_forbidden:
  use_cases:
    - Lorem
  parameters:
    - Siret de l'établissement
  format:
    - Donnée structurée JSON
  faq:
    - q: Nomenclature des spécialités
      a: |+
         La nomenclature des spécialités fournie par Carif Oref en juillet 2023 est la suivante : 
          | Code  | Intitulé de la formation                                        |
          |-------|----------------------------------------------------------------|
          | 100   | Formations générales                                           |
          | 110   | Spécialités pluriscientifiques                                 |
          | 111   | Physique-chimie                                               |
          | 112   | Chimie-biologie, biochimie                                    |
          | 113   | Sciences naturelles (biologie-géologie)                       |
          | 114   | Mathématiques (y compris maintenance mécano-électrique)       |
          | 115   | Physique                                                      |
          | 116   | Chimie                                                        |
          | 117   | Sciences de la terre                                          |
          | 118   | Sciences de la vie                                            |
          | 120   | Spécialités pluridisciplinaires, sciences humaines et droit avion|
          | 121   | Géographie                                                    |
          | 122   | Economie                                                      |
          | 123   | Sciences sociales (y compris démographie, anthropologie)      |
          | 124   | Psychologie                                                   |
          | 125   | Linguistique                                                  |
          | 126   | Histoire                                                      |
          | 127   | Philosophie, éthique et théologie                             |
          | 128   | Droit, sciences politiques                                    |
          | 130   | Spécialités littéraires et artistiques plurivalentes          |
          | 131   | Français, littérature et civilisation française               |
          | 132   | Arts plastiques                                               |
          | 133   | Musique, arts du spectacle                                    |
          | 134   | Autres disciplines artistiques et spécialités artistiques plurivalentes|
          | 135   | Langues et civilisations anciennes                            |
          | 136   | Langues vivantes, civilisations étrangères et régionales      |
          | 200   | Technologies industrielles fondamentales (génie industriel, procédés de Transformation, spécialités à dominante fonctionnelle)|
          | 201   | Technologies de commandes des transformations industriels (automatismes et robotique industriels, informatique industrielle)|
          | 210   | Spécialités plurivalentes de l'agronomie et de l'agriculture  |
          | 211   | Productions végétales, cultures spécialisées (horticulture, viticulture, arboriculture fruitière...)|
          | 212   | Productions animales, élevage spécialisé, aquaculture, soins aux animaux, y compris vétérinaire|
          | 213   | Forêts, espaces naturels, faune sauvage, pêche                 |
          | 214   | Aménagement paysager (parcs, jardins, espaces verts ...)      |
          | 220   | Spécialités pluritechnologiques des transformations           |
          | 221   | Agro-alimentaire, alimentation, cuisine                        |
          | 222   | Transformations chimiques et apparentées (y compris industrie pharmaceutique)|
          | 223   | Métallurgie (y compris sidérurgie, fonderie, non ferreux...)  |
          | 224   | Matériaux de construction, verre, céramique                    |
          | 225   | Plasturgie, matériaux composites                              |
          | 226   | Papier, carton                                                |
          | 227   | Energie, génie climatique (y compris énergie nucléaire, thermique, hydraulique)|
          | 230   | Spécialités pluritechnologiques, génie civil, construction, bois|
          | 231   | Mines et carrières, génie civil, topographie                   |
          | 232   | Bâtiment : construction et couverture                         |
          | 233   | Bâtiment : finitions                                          |
          | 234   | Travail du bois et de l'ameublement                            |
          | 240   | Spécialités pluritechnologiques matériaux souples             |
          | 241   | Textile                                                       |
          | 242   | Habillement (y compris mode, couture)                         |
          | 243   | Cuirs et peaux                                                |
          | 250   | Spécialités pluritechnologiques mécanique-électricité         |
          | 251   | Mécanique générale et de précision, usinage                   |
          | 252   | Moteurs et mécanique auto                                     |
          | 253   | Mécanique aéronautique et spatiale                            |
          | 254   | Structures métalliques (y compris soudure, carrosserie, coque bateau, cellule|
          | 255   | Electricité, électronique (non compris automatismes, productique)|
          | 300   | Spécialités plurivalentes des services                        |
          | 310   | Spécialités plurivalentes des échanges et de la gestion (y compris administration générale des entreprises et des collectivités)|
          | 311   | Transports, manutention, magasinage                           |
          | 312   | Commerce, vente                                               |
          | 313   | Finances, banque, assurances                                  |
          | 314   | Comptabilité, gestion                                         |
          | 315   | Ressources humaines, gestion du personnel, gestion de l'emploi|
          | 320   | Spécialités plurivalentes de la communication                 |
          | 321   | Journalisme, communication (y compris communication graphique et publicité)|
          | 322   | Techniques de l'imprimerie et de l'édition                    |
          | 323   | Techniques de l'image et du son, métiers connexes du spectacle|
          | 324   | Secrétariat, bureautique                                      |
          | 325   | Documentation, bibliothèques, administration des données      |
          | 326   | Informatique, traitement de l'information, réseaux de transmission des données|
          | 330   | Spécialités plurivalentes sanitaires et sociales              |
          | 331   | Santé                                                         |
          | 332   | Travail social                                                |
          | 333   | Enseignement, formation                                       |
          | 334   | Accueil, hôtellerie, tourisme                                 |
          | 335   | Animation culturelle, sportive et de loisirs                  |
          | 336   | Coiffure, esthétique et autres spécialités des services aux personnes|
          | 341   | Aménagement du territoire, développement, urbanisme          |
          | 342   | Protection et développement du patrimoine                     |
          | 343   | Nettoyage, assainissement, protection de l'environnement      |
          | 344   | Sécurité des biens et des personnes, police, surveillance (y compris hygiène et sécurité)|
          | 345   | Application des droits et statut des personnes                |
          | 346   | Spécialités militaires                                        |
          | 410   | Spécialités concernant plusieurs capacités                        |
          | 411   | Pratiques sportives (y compris : arts martiaux)                   |
          | 412   | Développement des capacités mentales et apprentissages de base    |
          | 413   | Développement des capacités comportementales et relationnelles    |
          | 414   | Développement des capacités individuelles d'organisation          |
          | 415   | Développement des capacités d'orientation, d'insertion ou de réinsertion sociales|
          | 421   | Jeux et activités spécifiques de loisirs                          |
          | 422   | Economie et activités domestiques                                 |
          | 423   | Vie familiale, vie sociale et autres formations au développement personnel|

