---
- uid: 'data_subvention/subventions'
  path: '/v3/data_subvention/subventions/{siren_or_siret_or_rna}'
  position: 152
  beta: true
  novelty: true # ou new_version: true / ou beta: true
  extra_description: |+
    Informations des dossiers de subventions déposés par les associations et de l'instruction avec les montants finalement accordés, avec parfois des données sur le paiement.
  perimeter:
    entity_type_description: |+
      Cette API concerne ✅ **les associations** ayant déposé des demandes de subventions depuis 2018 (l'historique pouvant parfois être antérieur).

    geographical_scope_description:  |+
      - ✅ **Métropole**, y compris Alsace-Moselle. <br> Les associations qui relèvent du **régime de droit local d'Alsace-Moselle** sont couvertes par l'API dès lors qu'elles sont immatriculées au répertoire Sirene ;
      - ✅ **DROM-COM** sauf ❌ les associations de Nouvelle-Calédonie, de la Polynésie française et de Wallis-et-Futuna qui ne sont pas immatriculées à l’INSEE, mais dans des bases locales.
    updating_rules_description: |+
      La date de mise à jour des données est spécifiée dans la réponse de l'API. La fréquence de mise à jour dépend du fournisseur et du type de données :

      **Données des demandes de subventions** : 
      - Les données issues du Fonds de coopération de la jeunesse et de l’éducation populaire (FONJEP) sont **mises à jour trimestriellement** ; 
      - Les données issues du compte Asso concernant surtout les demandes de subventions Jeunesse et Sports (FDVA, Partenariat JEP) sont **mises à jour trimestriellement** aussi ; 
      - Les données issues des demandes effectuées sur démarches-simplifiées.fr, notamment utilisé par les DRAC, la DIHAL, certaines DREETS et DDETS, sont **mises à jour en temps réel** ;
      - Les données des subventions versées au titre du Fonds interministériel de prévention contre la délinquance et la radicalisation (CIPDR) issues de l'outil Subventia, sont **mises à jour bi-annuellement** ;
      - La mise à jour des données des demandes de subventions Politique de la Ville, issues de Dauphin, est inconnue.

      **Données de paiements :** Elles proviennent toutes du logiciel Chorus, et sont **mises à jour hebdomadairement chaque lundi**

    know_more_description: |+
      [Cet article de Data.subvention](https://datasubvention.beta.gouv.fr/article-source-de-donnees-datasubvention/#elementor-toc__heading-anchor-2) détaille les sources de données de l'API.
    entities:
      - associations
  call_id: "SIRET / RNA"
  # La liste des clés disponible est stockée dans la locale `provider_uids` du fichier provider_uids.fr.yml
  provider_uids:
    - 'data_subvention'
  keywords:
    - 'whatever'
  data:
    description: |+
      Décrit le type / format des données délivrée par l'API. Le markdown GFM est supporté ici.

      # Pour ajouter un bloc de téléchargement pour un seul document PDF

      <div class="fr-downloads-group fr-downloads-group--bordered">    
        <h4 class="fr-downloads-group__title fr-text--lg fr-mb-1v">Exemple d'attestation&nbsp;:</h4>      
        <div class="fr-download">                
         <p>                    
          <a href="/files/exemple-fntp-carte-professionnelle-travaux-publics.pdf" download class="fr-download__link">
           Télécharger un exemple de carte professionnelle FNTP                       
           <span class="fr-download__detail">                            
           PDF – 623 Ko                        
           </span>                    
          </a>                
         </p>            
        </div>        
      </div>  

      # Pour ajouter un bloc de téléchargement pour plusieurs documents PDF

       <div class="fr-downloads-group fr-downloads-group--bordered">    
        <h4 class="fr-downloads-group__title fr-text--lg fr-mb-1v">Exemples de documents PDF&nbsp;:</h4>  
        <ul>        
         <li>            
          <div class="fr-download">                
           <p>                    
            <a href="/files/formulaire-unique-subventions-associations-cerfa_12156-06.pdf" download class="fr-download__link">
             Télécharger le document lorem ipsum sit dolores amet                        
             <span class="fr-download__detail">                            
             PDF – 161,88 Ko                        
             </span>                    
            </a>                
           </p>            
          </div>        
         </li>        
         <li>            
          <div class="fr-download">                
           <p>                    
            <a href="/files/formulaire-unique-subventions-associations-cerfa_12156-06.pdf" download class="fr-download__link">
             Télécharger le document lorem ipsum sit dolores amet                        
             <span class="fr-download__detail">                            
             PDF – 161,88 Ko                        
             </span>                    
            </a>                
           </p>            
          </div>        
         </li>        
        </ul>
      </div>        
  # Ne peut être que public ou protected
  opening: protected
  # Texte libre, cette donnée est affichée sur la page du endpoint
  use_cases_optional:
  use_cases_forbidden:
  use_cases:
    - Aides publiques
    - Marchés publics
    - Portail GRU - Préremplissage
    - Portail GRU - Instruction des démarches
    - Subventions associations
    - Détection de la fraude
  # Texte libre, cette donnée est affichée sur la page du endpoint
  parameters:
    - Numéro de SIREN de la personne physique ou morale recherchée
  format:
    - Donnée structurée JSON
  faq:
    - q: "Question ?"
      a: |+
        Réponse à la question. Le markdown GFM est supporté ici.
  historique: |+
    **Ce que change cette nouvelle version de l'API par rapport à la précédente :**
    Texte

    **Ce qui ne change pas :**
    Texte
  api_cgu:
    description: |+
        Les conditions d'utilisations spécifiques à l'API

