AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - 'config.ru'
  IgnoredMethods:
    - require
    - to
    - to_not

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%w': '()'

Style/CommentAnnotation:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/channels/**/*'
    - 'app/concepts/**/*'

Metrics/LineLength:
  Max: 110
  IgnoredPatterns:
    - '# TODO'

Style/SignalException:
  Exclude:
    - 'app/concepts/**/*'

Lint/UnreachableCode:
  Exclude:
    - 'app/concepts/**/*'

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - '_'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
