AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%w': '()'

Style/CommentAnnotation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  EnforcedStyle: require_parentheses
  IgnoreMacros: true
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInCamelCaseMethod: true
  AllowParenthesesInStringInterpolation: true

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  EnforcedStyle: single_quotes
