---
- uid: 'fntp/carte_professionnelle_travaux_public'
  path: '/v3/fntp/unites_legales/{siren}/carte_professionnelle_travaux_publics'
  position: 290
  perimeter:
    entity_type_description: |+
      Toutes les **entreprises de travaux publics** sont éligibles à demander une carte professionnelle à la FNTP.
      Au mois d'avril 2022, 7400 entreprises possédaient une carte professionnelle.

      ℹ️ Plus d'informations sur le [site de la FNTP](https://www.fntp.fr/outils/carte-professionnelle/tout-savoir-sur-la-carte-pro){:target="_blank"}
    entities:
      - entreprises
  call_id: "SIREN"
  provider_uids:
    - 'fntp'
  keywords:
    - 'conformité'
    - 'conforme'
    - 'obligations'
    - 'cotisations'
    - 'btp'
    - 'bâtiment'
    - 'travaux'
    - 'decret janvier 2019'
    - 'marchés publics'
    - 'Aides & subventions publiques'
    - 'fraude'
  data:
    description: |+
      Cette API délivre la carte professionnelle de travaux publics d'une entreprise, au format PDF, lorsque cette dernière est à jour de ses cotisations professionnelles Travaux Publics auprès de sa caisse de congés payés.
  opening: public
  format:
    - URL vers le document en PDF
  availability: 
    opening_time:
      7jours/7 et 24h/24
  use_cases:
    - Marchés publics
  use_cases_optional:
    - Aides & subventions publiques
    - Détection de la fraude
    - Portail GRU - Préremplissage
    - Portail GRU - Instruction des démarches
  use_cases_forbidden:
    - Subventions associations
  parameters:
    - Numéro de SIREN de l'entreprise
