---
- uid: 'ministere_interieur/associations'
  path: '/v4/ministere_interieur/api-asso/associations/{siren_or_rna}'
  position: 150
  perimeter: &association_perimeter
    entity_type_description: &association_entity_type_description |+
      Cette API concerne ✅ **les associations** inscrites au répertoire national des associations (RNA) et/ou au répertoire Sirene.

    geographical_scope_description: &association_geographical_scope_description |+
      Toutes les associations dont le siège se situe sur le territoire français :
      - ✅ Métropole
      - ✅ Outre-mer

      Les associations qui relèvent du ✅ **régime de droit local d'Alsace-Moselle** sont couvertes par l'API dès l'ors qu'elles sont immatriculées au répertoire Sirene.

    updating_rules_description: &association_updating_rules_description |+
      Les données sont **mises à jour quotidiennement** :

      - Les créations et modifications validées par les greffes des associations sont déversées et disponibles le lendemain dans le RNA.
      - Pour le répertoire Sirene, la mise à jour des données est faite quotidiennement entre 0h et 3h à l'Insee.

    entities: &association_entities
      - associations
  call_id: "SIREN / RNA"
  provider_uids: &association_provider_uids
    - 'mi'
  data:
    description: |+
      Cette API délivre des **informations sur l'unité légale de l'association** :
      - l'identité et les statuts (forme juridique, dates clés, état de l'association, statut utilité publique, régime, adresse de gestion) ;
      - la tranche effectif de salariés ;
      - les activités principales ;
      - les agréments de l'association ;
      - la liste des affiliations de l'association à des unions, fédérations ou réseaux, ainsi que des informations à leur sujet.

      ⚠️ Le type et la quantité d'informations disponibles par association sont variables car de nombreuses ressources sont soit déclaratives, soit déposées par les associations dans le cadre de démarches en ligne.

      Ces données sont issues de trois bases de ressources différentes :
      - le répertoire national des associations (RNA) ;
      - le répertoire Sirene ;
      - les données saisies par les associations dans [Le compte Asso](https://lecompteasso.associations.gouv.fr){:target="_blank"}, nommées documents administratifs complémentaires (DAC).

  opening: protected
  format: &association_format
    - Donnée structurée JSON
  availability: &association_availability
    opening_time:
      7jours/7 et 24h/24
  use_cases: &association_use_cases
    - Marchés publics
    - Aides & subventions publiques
    - Détection de la fraude
    - Portail GRU - Instruction des démarches
  parameters:
    - Numéro de SIREN ou numéro RNA de l’association
  faq: &association_faq
    - q: Une association utilisatrice de votre démarche s'est aperçue que ses informations ne sont plus à jour ?
      a: |+
        Vous pouvez l'orienter vers le [site officiel Le compte Asso](https://lecompteasso.associations.gouv.fr/declarer-un-changement-de-situation-de-mon-association/){:target="_blank"} où elle pourra déclarer son changement de situation.

- uid: 'ministere_interieur/unites_legales_open_data'
  path: '/v4/ministere_interieur/api-asso/associations/open_data/{siren_or_rna}'
  position: 150
  perimeter: *association_perimeter
  call_id: "SIREN / RNA"
  provider_uids: *association_provider_uids
  data:
    description: |+
      Cette API délivre des **informations publiques sur l'unité légale de l'association** :
      - l'identité et les statuts (forme juridique, dates clés, état de l'association, statut utilité publique, régime, adresse de gestion) ;
      - la tranche effectif de salariés ;
      - les activités principales.

      Ces données sont issues de deux bases de ressources différentes :
      - le répertoire national des associations ;
      - le répertoire Sirene.
  opening: public
  format: *association_format
  availability: *association_availability
  use_cases: *association_use_cases
  faq: *association_faq
