---
- uid: 'inpi/actes'
  path: '/v3/inpi/unites_legales/{siren}/actes'
  position: 160
  perimeter:
    entity_type_description: |+
      ✅ **Toutes les unités légales dont les actes ont été établis après 1993** par un greffe, ce qui représente environ 25 millions d'actes.
    updating_rules_description: |+
      Théoriquement, les actes sont transmis à l'INPI par le greffe dans un **délai de 24h**.
    entities:
      - entreprises
      - associations
  call_id: "SIREN"
  provider_uids:
    - 'inpi'
  data:
    description: |+
      Cette API délivre les actes d'une unité légale, fournis au format PDF, et comportant :
      - des **informations générales**, telles que la nature de l'archive, la date de dépôt en greffe, et le code greffe  ;
      - des informations sur le **capital social et sa répartition** ;
      - des informations sur les associés et tout ce qui est relatif à l’**administration de la société**.

      ℹ️ Dans le cas où un acte est manquant, si celui-ci est postérieur à 1993, l'INPI peut essayer de numériser le document qui fait défaut.
      Envoyez-nous votre demande détaillée en passant par le [support](<%= faq_index_path %>)
  opening: public
  format:
    - Donnée structurée JSON et URL vers l'acte
  use_cases:
    - Détection de la fraude
    - Aides publiques
    - Subventions associations
  use_cases_optional:
    - Marchés publics
    - Portail GRU - Préremplissage
    - Portail GRU - Instruction des démarches
  parameters:
    - Numéro de SIREN de l'unité légale.
