require 'rails_helper'

RSpec.describe 'private metrics', type: :feature do
  let!(:user_with_token)              { create(:user, :with_jwt) }
  let!(:user_with_inactive_token)     { create(:user, :with_jwt) }
  let!(:user_without_token)           { create(:user) }

  it 'works (dont want to test images generated by chartkick)' do
    allow_any_instance_of(UsedJwtIdsElasticQuery).to receive(:perform).and_return(
      user_with_inactive_token.jwt_api_entreprise.pluck(:id)
    )

    expect{ visit('/api/admin/private_metrics') }.not_to raise_error
  end
end
