# Check https://github.com/betagouv/signup-back/tree/master/docs/webhooks.md for all events and their details
---
development: &development
  created: &created {}
  updated: &updated {}
  team_member_updated: &team_member_updated {}
  send_application: &send_application
    emails:
      - template: 'send_application'
      - template: 'send_application_later'
        when: 'in 14 days'

  notify: &notify {}
  review_application: &review_application {}
  refuse_application: &refuse_application
    emails:
      - template: 'review_application'
        condition_on_authorization: 'demandeur_first_name_is_run?'

      - template: 'review_application_2'
        condition_on_authorization: 'demandeur_last_name_is_run?'
        to:
          - 'authorization_request.contact_technique'
        cc:
          - 'authorization_request.demandeur'

  validate_application: &validate_application {}

  create: *created
  update: *updated
  team_member_update: *team_member_updated
  submit: *send_application
  request_changes: *review_application
  refuse: *refuse_application
  validate: *validate_application

test: *development

production: &production
  created: &created
    emails:
      - template: 'embarquement_brouillon_en_attente'
        when: 'in 14 days'

  updated: &updated {}
  team_member_updated: &team_member_updated {}
  send_application: &send_application
    emails:
      - template: 'demande_recue'

      - template: 'reassurance_demande_recue'
        when: 'in 14 days'

  notify: &notify {}
  review_application: &review_application
    emails:
      - template: 'embarquement_modifications_demandees'

      - template: 'embarquement_relance_modifications_demandees'
        when: 'in 14 days'

  refuse_application: &refuse_application
    emails:
      - template: 'embarquement_demande_refusee'

  validate_application: &validate_application
    emails:
      - template: 'enquete_satisfaction'
        when: 'in 30 days'
        condition_on_authorization: 'not_editor_authorization_request'
        to:
          - 'authorization_request.demandeur'

      - template: 'embarquement_valide_to_demandeur_is_tech'
        condition_on_authorization: 'not_editor_and_all_contacts_have_the_same_email?'

      - template: 'embarquement_valide_to_demandeur_seulement'
        condition_on_authorization: 'not_editor_and_all_contacts_have_different_emails?'
        to:
          - 'authorization_request.demandeur'

      - template: 'embarquement_valide_to_tech_cc_demandeur'
        condition_on_authorization: 'not_editor_and_all_contacts_have_different_emails?'
        to:
          - 'authorization_request.contact_technique'
        cc:
          - 'authorization_request.demandeur'

  create: *created
  update: *updated
  team_member_update: *team_member_updated
  submit: *send_application
  request_changes: *review_application
  refuse: *refuse_application
  validate: *validate_application

sandbox: *production
staging: *production
