# Check https://github.com/betagouv/signup-back/tree/master/docs/webhooks.md for all events and their details
---
development: &development
  created: {}
  updated: &updated {}
  team_member_updated: &team_member_updated {}
  send_application: &send_application
    emails:
      - template: 'send_application'

  notify: &notify {}
  review_application: &review_application {}
  refuse_application: &refuse_application
    emails:
      - template: 'review_application'
        condition_on_authorization: 'demandeur_first_name_is_run?'

      - template: 'review_application_2'
        condition_on_authorization: 'demandeur_last_name_is_run?'
        to:
          - 'authorization_request.contact_metier'
        cc:
          - 'authorization_request.contact_technique'
          - 'authorization_request.demandeur'

  approve: &approve
    emails:
      - template: 'embarquement_valide_to_editeur'
        to:
          - 'authorization_request.demandeur'

  create: {}
  update: *updated
  team_member_update: *team_member_updated
  submit: *send_application
  request_changes: *review_application
  refuse: *refuse_application
  validate: *approve

test: *development

production: &production
  created: {}
  updated: &updated {}
  team_member_updated: &team_member_updated {}
  send_application: &send_application
    emails:
      - template: 'demande_recue'
        on_update: true

  notify: &notify {}
  review_application: &review_application
    emails:
      - template: 'embarquement_modifications_demandees'
        on_update: true

  refuse_application: &refuse_application
    emails:
      - template: 'embarquement_demande_refusee'
        on_update: true

  approve: &approve
    emails:
      - template: 'embarquement_valide_to_editeur'
        condition_on_authorization: 'editor_authorization_request?'
        to:
          - 'authorization_request.demandeur'
        cc:
          - 'authorization_request.contact_technique'
          - 'authorization_request.contact_metier'

      - template: 'update_embarquement_valide_to_demandeur'
        only_on_update: true
        condition_on_authorization: 'not_editor_authorization_request?'
        to:
          - 'authorization_request.contact_metier'
        cc:
          - 'authorization_request.contact_technique'
          - 'authorization_request.demandeur'

      - template: 'embarquement_valide_to_demandeur_is_tech_is_metier'
        condition_on_authorization: 'not_editor_and_all_contacts_have_the_same_email?'

      - template: 'embarquement_valide_to_demandeur_seulement'
        condition_on_authorization: 'not_editor_and_demandeur_different_to_other_contacts?'
        to:
          - 'authorization_request.demandeur'

      - template: 'embarquement_valide_to_tech_cc_demandeur_metier'
        condition_on_authorization: 'not_editor_and_demandeur_different_to_other_contacts?'
        to:
          - 'authorization_request.contact_technique'
        cc:
          - 'authorization_request.demandeur'

      - template: 'embarquement_valide_to_metier_cc_demandeur_tech'
        condition_on_authorization: 'not_editor_and_demandeur_different_to_other_contacts?'
        to:
          - 'authorization_request.contact_metier'
        cc:
          - 'authorization_request.demandeur'
          - 'authorization_request.contact_technique'

      - template: 'embarquement_valide_to_metier_cc_demandeur_tech'
        condition_on_authorization: 'not_editor_and_user_is_contact_technique_and_not_contact_metier?'
        to:
          - 'authorization_request.contact_metier'
        cc:
          - 'authorization_request.demandeur'

      - template: 'embarquement_valide_to_demandeur_is_metier_not_tech'
        condition_on_authorization: 'not_editor_and_user_is_contact_metier_and_not_contact_technique?'
        to:
          - 'authorization_request.demandeur'

      - template: 'embarquement_valide_to_tech_cc_demandeur_metier'
        condition_on_authorization: 'not_editor_and_user_is_contact_metier_and_not_contact_technique?'
        to:
          - 'authorization_request.contact_technique'
        cc:
          - 'authorization_request.demandeur'

      - template: 'embarquement_valide_to_demandeur_is_tech_not_metier'
        condition_on_authorization: 'not_editor_and_user_is_contact_technique_and_not_contact_metier?'
        to:
          - 'authorization_request.demandeur'

  update: *updated
  team_member_update: *team_member_updated
  submit: *send_application
  request_changes: *review_application
  refuse: *refuse_application
  validate: *approve

sandbox: *production
staging: *production
