en:
  errors:
    unique?: 'value already exists'

    datetime?: 'must be a datetime format'

    role_exists?: 'role "%{code}" does not exist'

    user_exists?: 'user with ID "%{uid}" does not exist'
    email_exists?: 'user with email "%{email}" does not exist'

    pwd_token_exists?: 'Le lien de régénération de mot de passe est invalide'
