shared:
  components:
    entreprises: ckob7hc0j1082711g5oi6ae2pdhi # Données de référence d'une entité ( /entreprises ) ( INSEE, Infogreffe )
    etablissements: ckob7hju21100551eomzovzcvvrg # Données de référence d'un établissement ( /etablissements ) ( INSEE )
    exercices: ckobac2u8335924eomzwvlq0vyt # Chiffre d'affaires ( /exercices ) ( DGFIP )
    bilans_inpi: ckok0s9la300691c1oivr221sby # Bilans annuels ( /bilans_inpi ) ( INPI )
    bilans_entreprise_bdf: ckok0soo81070493cumxbs9lonrm # 3 derniers bilans annuels ( /bilans_entreprises_bdf ) ( Banque de France )
    liasse_fiscale: ckok0t57c1074150cumxcej92w9n # Déclarations de résultat ( /liasses_fiscales_dgfip ) ( DGFIP )
    extraits_rcs: ckok0usze321029c1oi84kximz0 # Extrait RCS ( /extraits_rcs_infogreffe ) ( Infogreffe )
    associations: ckok0v39p323297c1oi95srwyv9 # Informations déclaratives d’une association ( /associations ) ( RNA )
    documents_association: ckok0vgrv328492c1oieff16gvn # Divers documents d'une association ( /documents_associations ) ( RNA )
    actes_inpi: ckok0whwn1104072cumxr95yghqh # Actes ( /actes_inpi ) ( INPI )
    conventions_collectives: ckok0wyqr1107604cumxbx3gphcj # Conventions collectives ( /conventions_collectives ) ( Fabrique numérique des Ministères Sociaux )
    entreprises_artisanales: ckok0xazp1110327cumxsotr9a7q # Données de référence d'une entreprise artisanale ( /entreprises_artisanales_cma ) ( CMA France )
    effectifs_acoss: ckok0y8mj1117609cumxruy9g8i3 # Effectifs d'une entreprise ( /effectifs_..._acoss_covid ) ( URSSAF )
    eori_douanes: ckok0yj4i353963c1oiuf5jogod # Immatriculation EORI ( /eori_douanes ) ( Douanes )
    attestations_fiscales: ckok0ztz71130840cumxhun0f58v # Attestation fiscale ( /attestations_fiscales_dgfip ) ( DGFIP )
    attestations_sociales: ckok109vj1134691cumxv2f63wii # Attestation de vigilance ( /attestations_sociales_acoss ) ( ACOSS )
    attestations_agefiph: ckok10x181140548cumxkjd86l1z # Conformité emploi des travailleurs handicapés ( /attestations_agefiph ) ( AGEFIPH )
    msa_cotisations: ckok117pj1143550cumxulz1udjy # Cotisations de sécurité sociale agricole ( /cotisations_msa ) ( MSA )
    probtp: ckok11hh6379152c1oirzidg8qe # Cotisations retraite bâtiment ( /cotisation_retraite_probtp ) ( ProBTP )
    fntp_carte_pro: ckok11qdj1151290cumxlfoix2yk # Carte professionnelle travaux publics ( /cartes_professionnelles_fntp ) ( FNTP )
    certificat_cnetp: ckok11zz71153210cumx2vmm6ewk # Cotisations congés payés & chômage intempéries ( /certificats_cnetp ) ( CNETP )
    certificat_agence_bio: ckok12e5u388956c1oipujpr1zs # Certification en BIO ( /certificats_agence_bio ) ( Agence BIO )
    certificat_rge_ademe: ckok12qor392025c1ois0x52wdn # Certification RGE ( /certificats_rge_ademe ) ( ADEME )
    qualibat: ckok12z22393980c1oi51wna9zg # Certificat de qualification bâtiment ( /certificats_qualibat ) ( Qualibat )
    certificat_opqibi: ckok1395e396377c1oil3sqo3ux # Certification de qualification d'ingénierie ( /certificats_opqibi ) ( OPQIBI )
    extrait_court_inpi: ckok13lcf399221c1oicn4n4xos # Brevets, modèles et marques déposés ( /extraits_courts_inpi ) ( INPI )

# Rails.application.config_for(:instatus).dig(:components, :entreprises) # => "ckob7hc0j1082711g5oi6ae2pdhi"
