env:
  CI: true
  COVERAGE: true

name: Tests + merge develop->master
on: [push]
jobs:
  test:
    name: Tests (RSpec)
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin_apientreprise
          POSTGRES_PASSWORD: wow*verysecret
          POSTGRES_DB: admin_apientreprise_test
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    steps:
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 321

      - name: Install postgres client #and imagemagick
        run: sudo apt-get install libpq-dev #imagemagick

      - name: Create database users
        env:
          POSTGRES_USER: admin_apientreprise
          POSTGRES_DB: admin_apientreprise_test
          PGPASSWORD: wow*verysecret
        run: |
          psql -h localhost -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -f `pwd`/postgresql_setup.txt

      - name: Create database
        run: bundle exec rails db:create db:schema:load RAILS_ENV=test

      - name: Run tests
        run: bundle exec rspec

      - uses: joshmfrankel/simplecov-check-action@main
        if: "${{ github.actor != 'dependabot[bot]' }}"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_suite_coverage: 95

      - name: Import GPG key to sign master push
        if: github.ref == 'refs/heads/develop'
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Force push develop to master
        if: github.ref == 'refs/heads/develop'
        run: |
          git reset --hard && \
            git push --force origin develop:fake_master && \
            git fetch && \
            [[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow
          exit 0
